"""The migration generator must not propose deleting existing supported data."""

import sqlite3
import warnings
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy.exc import SAWarning

from autoflow.infrastructure.database import session as database_session


def test_fresh_migrated_database_matches_registered_metadata(tmp_path):
    database = tmp_path / "metadata.sqlite3"
    database_session.migrate_database(database)
    database_session.migrate_database(database)
    config = Config(str(Path(database_session.__file__).with_name("alembic.ini")))
    config.set_main_option("sqlalchemy.url", f"sqlite:///{database}")
    with warnings.catch_warnings():
        warnings.simplefilter("error", SAWarning)
        command.check(config)
    with sqlite3.connect(database) as connection:
        tables = {row[0] for row in connection.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        assert {"android_operations", "project_workflow_debug_commands", "proxy_projections"} <= tables
        assert connection.execute("PRAGMA foreign_key_check").fetchall() == []
        assert connection.execute("PRAGMA integrity_check").fetchone() == ("ok",)
        assert sum(row[2] == "project_data_generations" for row in connection.execute("PRAGMA foreign_key_list(project_data_tables)")) == 3


@pytest.mark.parametrize("damage", [
    "DROP INDEX uq_proxy_remote_active",
    "ALTER TABLE project_sheets_bindings DROP COLUMN identity_verification",
    "CREATE TABLE unexpected_unmapped_table (id INTEGER PRIMARY KEY)",
])
def test_metadata_gate_still_detects_real_drift(tmp_path, damage):
    database = tmp_path / "drift.sqlite3"
    database_session.migrate_database(database)
    with sqlite3.connect(database) as connection:
        connection.execute(damage)
    config = Config(str(Path(database_session.__file__).with_name("alembic.ini")))
    config.set_main_option("sqlalchemy.url", f"sqlite:///{database}")
    with pytest.raises(AutogenerateDiffsDetected):
        command.check(config)
