from collections.abc import Awaitable, Callable
from contextlib import AbstractContextManager
from typing import Protocol

from .models import (
    DefaultKernel,
    InstalledKernel,
    KernelCatalog,
    KernelRef,
    LicenseStatus,
)


class KernelCatalogProvider(Protocol):
    async def catalog(self) -> KernelCatalog: ...
    def installed(self) -> list[InstalledKernel]: ...
    def is_installed(self, edition: str, version: str) -> bool: ...


class LicenseStore(Protocol):
    def read(self) -> str | None: ...
    def write(self, value: str) -> None: ...
    def delete(self) -> None: ...


LicenseValidator = Callable[[str], Awaitable[LicenseStatus]]


class DefaultKernelRepository(Protocol):
    def get(self) -> DefaultKernel: ...
    def compare_and_set(
        self, expected_revision: int, kernel: KernelRef | None
    ) -> DefaultKernel: ...
    def clear_if_matches(self, kernel: KernelRef) -> DefaultKernel: ...


class KernelInstallationStore(Protocol):
    def guard(
        self, kernel: KernelRef | None = None
    ) -> AbstractContextManager[None]: ...
    def license_guard(self) -> AbstractContextManager[None]: ...
    def stage(self, kernel: KernelRef) -> str: ...
    def restore(self, token: str) -> None: ...
    def purge(self, token: str) -> None: ...
