import { Disclosure } from '../../../shared/components/ui/disclosure'
import { ArrowClockwise, Database, Desktop, FileText, FolderOpen, Info, PlugsConnected, SignOut } from '@phosphor-icons/react'
import { useEffect, useRef, useState } from 'react'
import type { DesktopSettingsSnapshot, SettingsBridge, SettingsDirectory, UiPreferences, WorkspaceChoice } from '../../../../shared/settings'
import { Modal } from '../../../shared/components/Modal'
import { Toaster, notify } from '../../../shared/components/Toaster'
import { Button } from '../../../shared/components/ui/button'
import { Select } from '../../../shared/components/ui/select'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../../../shared/components/ui/tabs'
import { DetailGrid, SettingsCard } from '../components/SettingsCard'
import { DiagnosticDialog } from '../components/DiagnosticDialog'

type Props = { bridge: SettingsBridge; restartService(): Promise<unknown>; onServiceChanged?(): void }
function unwrap<T>(result: { ok: true; value: T } | { ok: false; error: { message: string } }): T { if (!result.ok) throw new Error(result.error.message); return result.value }
const serviceCopy = { starting: ['正在启动', '本地服务正在启动，请稍候。'], ready: ['运行正常', '本地服务已连接。'], failed: ['启动失败', '请查看错误信息并重试。'], stopped: ['已停止', '本地服务当前未运行。'] } as const

export function SettingsPage({ bridge, restartService, onServiceChanged }: Props) {
  const [data, setData] = useState<DesktopSettingsSnapshot | null>(null)
  const [loadError, setLoadError] = useState('')
  const [operationError, setOperationError] = useState('')
  const [action, setAction] = useState<'preference' | 'restart' | 'choose' | 'switch' | 'open' | 'quit' | null>(null)
  const [choice, setChoice] = useState<WorkspaceChoice | null>(null)
  const [workspaceResult, setWorkspaceResult] = useState('')
  const [diagnostics, setDiagnostics] = useState(false)
  const [tab, setTab] = useState('general')
  const pendingPreferences = useRef<UiPreferences | null>(null)
  const showedRequiredSelection = useRef(false)

  async function refresh() { try { const next = unwrap(await bridge.getSettings()); setData({ ...next, preferences: pendingPreferences.current ?? next.preferences }); setLoadError('') } catch (cause) { setLoadError(cause instanceof Error ? cause.message : '设置读取失败') } }
  useEffect(() => { let disposed = false; let timer: number | undefined; const poll = async () => { if (!disposed) await refresh(); if (!disposed) timer = window.setTimeout(poll, 1000) }; void poll(); return () => { disposed = true; if (timer) window.clearTimeout(timer) } }, [bridge])
  useEffect(() => { if (data?.workspace.needsSelection && !showedRequiredSelection.current) { showedRequiredSelection.current = true; setTab('workspace') } }, [data?.workspace.needsSelection])
  const busy = action !== null || data?.operation !== 'idle'

  async function preference(next: UiPreferences) { if (!data || busy) return; const previous = data.preferences; pendingPreferences.current = next; setAction('preference'); setOperationError(''); setData({ ...data, preferences: next }); try { const saved = unwrap(await bridge.setPreferences(next)); pendingPreferences.current = null; setData(current => current ? { ...current, preferences: saved } : current); notify({ title: '设置已保存', tone: 'success' }) } catch (cause) { pendingPreferences.current = null; setData(current => current ? { ...current, preferences: previous } : current); setOperationError(cause instanceof Error ? cause.message : '设置保存失败') } finally { setAction(null) } }
  async function restart() { if (busy || data?.workspace.blocked) return; setAction('restart'); setOperationError(''); try { await restartService(); onServiceChanged?.(); await refresh() } catch (cause) { setOperationError(cause instanceof Error ? cause.message : '本地服务重启失败') } finally { setAction(null) } }
  async function choose(source: 'choose' | 'previous') { if (busy || data?.workspace.blocked) return; setAction('choose'); setOperationError(''); setWorkspaceResult(''); try { const selected = unwrap(await bridge.chooseWorkspace(source)); if (selected) setChoice(selected) } catch (cause) { setOperationError(cause instanceof Error ? cause.message : '工作区选择失败') } finally { setAction(null) } }
  async function confirm() { if (!choice) return; setAction('switch'); setOperationError(''); try { setData(unwrap(await bridge.confirmWorkspace(choice.id))); setChoice(null); onServiceChanged?.(); notify({ title: '工作区已切换', tone: 'success' }) } catch (cause) { setChoice(null); setWorkspaceResult(cause instanceof Error ? cause.message : '切换失败，恢复结果未知') } finally { setAction(null) } }
  async function open(directory: SettingsDirectory) { if (busy) return; setAction('open'); setOperationError(''); try { unwrap(await bridge.openSettingsDirectory(directory)) } catch (cause) { setOperationError(cause instanceof Error ? cause.message : '目录打开失败') } finally { setAction(null) } }
  async function quit() { if (busy) return; setAction('quit'); setOperationError(''); try { unwrap(await bridge.quitApplication()) } catch (cause) { setOperationError(cause instanceof Error ? cause.message : '退出请求失败'); setAction(null) } }

  if (!data && !loadError) return <main className="min-h-dvh bg-canvas p-8" role="status">正在加载设置…</main>
  if (!data) return <main className="grid min-h-dvh place-content-center bg-canvas text-center"><p role="alert">{loadError}</p><Button onClick={() => void refresh()}>重试</Button></main>
  const status = serviceCopy[data.service.state]
  return <main className="min-h-dvh bg-canvas px-4 py-7 text-ink sm:px-6 lg:px-8"><div className="mx-auto w-full max-w-[1050px]"><header><h1 className="m-0 text-3xl font-semibold">设置</h1><p className="mb-0 mt-1 text-muted">管理本机应用与工作区</p></header>{loadError ? <div role="alert" className="mt-4 rounded-control border border-warning/30 bg-warning-soft p-3 text-sm text-warning">状态更新失败：{loadError}</div> : null}{operationError ? <div role="alert" className="mt-4 flex items-center justify-between gap-3 rounded-control border border-danger/30 bg-danger-soft p-3 text-sm text-danger"><span>{operationError}</span><Button className="h-8" onClick={() => setOperationError('')}>关闭</Button></div> : null}{data.workspace.recovery ? <div role="status" className="mt-4 rounded-control border border-warning/30 bg-warning-soft p-3 text-sm text-warning">{data.workspace.recovery}</div> : null}
    <Tabs value={tab} onValueChange={setTab} className="mt-5"><TabsList className="w-full justify-start gap-5"><TabsTrigger value="general">常规</TabsTrigger><TabsTrigger value="workspace">工作区</TabsTrigger><TabsTrigger value="about">关于</TabsTrigger></TabsList>
      <TabsContent value="general" className="grid gap-5"><SettingsCard icon={PlugsConnected} title="本地服务" description={status[1]} action={<span className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-sm font-medium ${data.service.state === 'ready' ? 'bg-sage-soft text-sage-strong' : data.service.state === 'failed' ? 'bg-danger-soft text-danger' : 'bg-surface-subtle text-muted'}`}>{status[0]}</span><Button disabled={busy || data.workspace.blocked || data.service.state === 'starting'} onClick={() => void restart()}><ArrowClockwise />{action === 'restart' ? '正在重启…' : data.service.state === 'stopped' ? '启动服务' : '重启服务'}</Button></span>}><DetailGrid items={[{ label: '访问范围', value: data.service.baseUrl ? '仅限本机' : '不可用' }, { label: 'API 版本', value: data.service.apiVersion ?? '不可用' }]} />{data.service.message ? <p className="mt-4 text-sm text-muted">{data.service.message}</p> : null}<Disclosure className="mt-4" summary="连接详情"><DetailGrid items={[{ label: '监听地址', value: data.service.baseUrl ?? '不可用' }, { label: '连接方式', value: data.service.baseUrl ? 'Loopback HTTP' : '不可用' }]} /></Disclosure></SettingsCard>
        <SettingsCard icon={Database} title="本地数据" description="业务数据保存在当前工作区。" action={<Button disabled={busy} onClick={() => setTab('workspace')}>管理工作区</Button>}><DetailGrid items={[{ label: '存储方式', value: 'SQLite' }, { label: '当前工作区', value: data.workspace.path }]} /></SettingsCard>
        <SettingsCard icon={Desktop} title="界面体验"><div className="grid gap-4"><label className="grid items-center gap-2 sm:grid-cols-[1fr_13rem]"><span><strong className="block">界面缩放</strong><small className="text-muted">调整文字和控件的显示大小。</small></span><Select clearable={false} aria-label="界面缩放" disabled={busy} value={String(data.preferences.zoom)} onValueChange={e => void preference({ ...data.preferences, zoom: Number((e ?? '100')) as UiPreferences['zoom'] })} options={[...[90,100,110,125].map(value => ({ value: String(value), label: String(value) + "%" }))]} /></label><label className="grid items-center gap-2 border-t border-line pt-4 sm:grid-cols-[1fr_13rem]"><span><strong className="block">减少动效</strong><small className="text-muted">调整弹窗、提示和加载动画。</small></span><Select clearable={false} aria-label="减少动效" disabled={busy} value={data.preferences.motion} onValueChange={e => void preference({ ...data.preferences, motion: (e ?? 'system') as UiPreferences['motion'] })} options={[{ value: "system", label: "跟随系统" }, { value: "reduce", label: "减少动效" }, { value: "full", label: "完整动效" }]} /></label></div></SettingsCard></TabsContent>
      <TabsContent value="workspace"><div className="grid gap-5"><SettingsCard icon={FolderOpen} title="当前工作区" description={data.workspace.blocked ? `任务进行中，暂时无法切换：${data.workspace.blockers.join('；')}` : '切换工作区不会搬迁当前数据。'} action={<span className="flex flex-wrap gap-2"><Button onClick={() => void open('workspace')}>打开目录</Button><Button variant="primary" disabled={busy || data.workspace.blocked} onClick={() => void choose('choose')}>切换工作区</Button>{data.workspace.previousPath ? <Button disabled={busy || data.workspace.blocked} onClick={() => void choose('previous')}>切回上一个</Button> : null}</span>}><code className="block overflow-auto rounded-control bg-surface-subtle p-3 text-sm">{data.workspace.path}</code></SettingsCard><SettingsCard icon={Database} title="工作区位置" description="当前工作区内的主要文件与目录。"><div className="divide-y divide-line">{([['database','数据库'],['profiles','浏览器配置'],['kernels','浏览器内核'],['logs','运行日志']] as Array<[SettingsDirectory,string]>).map(([key,label]) => <div key={key} className="grid items-center gap-3 py-3 sm:grid-cols-[9rem_1fr_auto]"><strong>{label}</strong><code className="min-w-0 overflow-hidden text-ellipsis text-xs text-muted">{data.workspace.paths[key]}</code><Button onClick={() => void open(key)}>打开目录</Button></div>)}</div></SettingsCard></div></TabsContent>
      <TabsContent value="about"><div className="grid gap-5"><SettingsCard icon={Info} title="AutoFlow" description="本地浏览器自动化工作台。"><DetailGrid items={[{ label: '应用版本', value: data.runtime.appVersion }, { label: '当前平台', value: `${data.runtime.platform} · ${data.runtime.arch}` }]} /><Disclosure className="mt-4" summary="运行环境"><div className="mt-4"><DetailGrid items={[{label:'桌面运行时',value:`Electron ${data.runtime.electronVersion} · Chrome ${data.runtime.chromeVersion} · Node ${data.runtime.nodeVersion}`},{label:'本地服务',value:data.runtime.backendVersion ? `${data.runtime.backendVersion} · Python ${data.runtime.pythonVersion ?? '不可用'}` : '不可用'},{label:'数据存储',value:`SQLite ${data.runtime.sqliteVersion ?? '不可用'}`}]}/></div></Disclosure></SettingsCard><SettingsCard icon={FileText} title="排查问题" description="导出基础诊断信息，便于定位本地问题。" action={<Button variant="primary" onClick={() => setDiagnostics(true)}>导出诊断信息</Button>} /><SettingsCard icon={SignOut} title="退出应用" description={data.runtime.platform === 'macos' ? '关闭窗口后应用仍会运行；退出应用会停止本地服务。' : '关闭最后一个窗口会退出 AutoFlow；退出前将停止本地服务。'} action={<Button disabled={busy} onClick={() => void quit()}>退出应用</Button>} /></div></TabsContent>
    </Tabs></div><Modal open={Boolean(choice || workspaceResult)} onOpenChange={open => { if (!open && action !== 'switch') { setChoice(null); setWorkspaceResult('') } }} closeDisabled={action === 'switch'} title={workspaceResult ? '工作区切换未完成' : '切换工作区'} description={workspaceResult || (choice?.kind === 'empty' ? '将初始化新的 AutoFlow 工作区。' : '已识别 AutoFlow 工作区。')} footer={workspaceResult ? <><Button onClick={() => setWorkspaceResult('')}>关闭</Button><Button variant="primary" onClick={() => { setWorkspaceResult(''); void choose('choose') }}>重新选择</Button></> : <><Button autoFocus disabled={action === 'switch'} onClick={() => setChoice(null)}>取消</Button><Button variant="primary" disabled={action === 'switch'} onClick={() => void confirm()}>{action === 'switch' ? '正在切换…' : '确认切换'}</Button></>}>{workspaceResult ? <div role="alert" className="rounded-control border border-danger/30 bg-danger-soft p-3 text-sm text-danger">选择凭据已失效，不会重复提交。请核对恢复结果后重新选择工作区。<br />{workspaceResult}</div> : <><dl className="grid gap-3"><div><dt className="text-sm text-muted">当前</dt><dd className="m-0 break-all font-mono text-sm">{data.workspace.path}</dd></div><div><dt className="text-sm text-muted">目标</dt><dd className="m-0 break-all font-mono text-sm">{choice?.path}</dd></div></dl><p className="rounded-control bg-clay-soft p-3 text-sm text-clay">将连接目标工作区；当前数据仍保留在原目录。</p></>}</Modal><DiagnosticDialog open={diagnostics} bridge={bridge} onOpenChange={setDiagnostics} /><Toaster /></main>
}
