from copy import deepcopy
from typing import Any

# Project tasks reuse the approved browser bridge and pure-data executors.
# Families with additional resource ports stay gated until those ports are wired.
_RUNNABLE_MODULES = (
    ("condition", "条件判断"),
    ("loop", "循环"),
    ("foreach", "遍历列表"),
    ("foreach_dict", "遍历字典"),
    ("infinite_loop", "无限循环"),
    ("break_loop", "退出循环"),
    ("continue_loop", "跳过本轮"),
    ("set_variable", "设置变量"),
    ("increment_decrement", "自增自减"),
    ("json_parse", "JSON解析"),
    ("random_number", "生成随机数"),
    ("get_time", "获取时间"),
    ("print_log", "打印日志"),
    ("export_log", "导出日志"),
    ("table_add_row", "添加数据行"),
    ("table_add_column", "添加数据列"),
    ("table_set_cell", "设置单元格"),
    ("table_get_cell", "获取单元格"),
    ("table_delete_row", "删除数据行"),
    ("table_clear", "清空数据表"),
    ("table_export", "导出数据表"),
    ("extract_table_data", "提取表格数据"),
    ("api_request", "HTTP请求"),
    ("api_trigger", "API触发器"),
    ("webhook_request", "Webhook请求"),
    ("notify_webhook", "Webhook通知"),
    ("wait", "等待"),
    ("scheduled_task", "定时任务"),
    ("probability_trigger", "概率触发器"),
    ("assert_checkpoint", "断言检查点"),
    ("stop_workflow", "停止工作流"),
    ("network_capture", "浏览器网络抓包"),
    ("network_monitor_start", "开始网络监听"),
    ("network_monitor_wait", "等待网络请求"),
    ("network_monitor_stop", "停止网络监听"),
    ("allure_init", "Allure初始化"),
    ("allure_start_test", "开始测试用例"),
    ("allure_add_step", "添加测试步骤"),
    ("allure_add_attachment", "添加附件"),
    ("allure_stop_test", "结束测试用例"),
    ("allure_generate_report", "生成测试报告"),
    ("ssh_connect", "SSH连接"),
    ("ssh_execute_command", "SSH执行命令"),
    ("ssh_upload_file", "SSH上传文件"),
    ("ssh_download_file", "SSH下载文件"),
    ("ssh_disconnect", "SSH断开连接"),
    ("subflow", "子流程"),
    ("run_workflow_file", "运行工作流"),
    ("ai_chat", "AI对话"),
    ("ai_classify", "AI文本分类"),
    ("ai_dedup_semantic", "AI语义去重"),
    ("ai_element_selector", "AI元素选择"),
    ("ai_extract", "AI信息抽取"),
    ("ai_generate_image", "AI生成图片"),
    ("ai_generate_video", "AI生成视频"),
    ("ai_normalize", "AI数据规整"),
    ("ai_route", "AI智能路由"),
    ("ai_sentiment", "AI情感分析"),
    ("ai_smart_scraper", "AI智能爬虫"),
    ("ai_summarize", "AI文本摘要"),
    ("ai_translate", "AI翻译"),
    ("ai_vision", "图像识别"),
    ("ai_vision_act", "AI视觉操作"),
    ("open_page", "打开网页"),
    ("input_text", "输入文本"),
    ("click_element", "点击元素"),
    ("get_element_info", "读取文本"),
    ("screenshot", "网页截图"),
    ("use_opened_page", "使用已打开网页"),
    ("close_page", "关闭网页"),
    ("refresh_page", "刷新网页"),
    ("go_back", "后退"),
    ("go_forward", "前进"),
    ("switch_iframe", "切换 iframe"),
    ("switch_to_main", "切回主页面"),
    ("switch_tab", "切换标签页"),
    ("hover_element", "悬停元素"),
    ("handle_dialog", "处理弹窗"),
    ("inject_javascript", "注入 JavaScript"),
    ("wait_element", "等待元素"),
    ("wait_page_load", "等待页面加载完成"),
    ("page_load_complete", "网页是否加载完成"),
    ("select_dropdown", "选择下拉选项"),
    ("set_checkbox", "设置复选框"),
    ("drag_element", "拖拽元素"),
    ("scroll_page", "滚动页面"),
    ("upload_file", "上传文件"),
    ("download_file", "下载文件"),
    ("save_image", "保存图片"),
    ("get_child_elements", "获取子元素"),
    ("get_sibling_elements", "获取兄弟元素"),
    ("element_exists", "元素是否存在"),
    ("element_visible", "元素是否可见"),
    ("csv_generate", "CSV生成"),
    ("csv_parse", "CSV解析"),
    ("dict_deep_copy", "字典深拷贝"),
    ("dict_filter", "字典过滤"),
    ("dict_flatten", "字典扁平化"),
    ("dict_get_path", "字典路径取值"),
    ("dict_invert", "字典反转"),
    ("dict_map_values", "字典映射值"),
    ("dict_merge", "字典合并"),
    ("dict_sort", "字典排序"),
    ("list_cartesian_product", "列表笛卡尔积"),
    ("list_chunk", "列表分组"),
    ("list_count", "列表计数"),
    ("list_difference", "列表差集"),
    ("list_filter", "列表过滤"),
    ("list_find", "列表查找"),
    ("list_flatten", "列表扁平化"),
    ("list_intersection", "列表交集"),
    ("list_map", "列表映射"),
    ("list_merge", "列表合并"),
    ("list_remove_empty", "列表去空"),
    ("list_reverse", "列表反转"),
    ("list_sample", "列表采样"),
    ("list_shuffle", "列表随机打乱"),
    ("list_to_string_advanced", "列表转字符串（高级）"),
    ("list_union", "列表并集"),
    ("list_operation", "列表操作"),
    ("list_get", "列表取值"),
    ("list_length", "列表长度"),
    ("list_export", "列表导出"),
    ("dict_operation", "字典操作"),
    ("dict_get", "字典取值"),
    ("dict_keys", "字典键列表"),
    ("list_sum", "列表求和"),
    ("list_average", "列表求平均值"),
    ("list_max", "列表求最大值"),
    ("list_min", "列表求最小值"),
    ("list_sort", "列表排序"),
    ("list_unique", "列表去重"),
    ("list_slice", "列表截取"),
    ("math_round", "四舍五入"),
    ("math_base_convert", "进制转换"),
    ("math_floor", "取整"),
    ("math_modulo", "求余"),
    ("math_abs", "绝对值"),
    ("math_sqrt", "开次方"),
    ("math_power", "求次方"),
    ("math_log", "对数运算"),
    ("math_trig", "三角函数"),
    ("math_exp", "指数运算"),
    ("math_gcd", "最大公约数"),
    ("math_lcm", "最小公倍数"),
    ("math_factorial", "阶乘"),
    ("math_permutation", "排列组合"),
    ("math_percentage", "百分比计算"),
    ("math_clamp", "数字范围限制"),
    ("math_random_advanced", "随机数生成（高级）"),
    ("stat_median", "中位数"),
    ("stat_mode", "众数"),
    ("stat_variance", "方差"),
    ("stat_stdev", "标准差"),
    ("stat_percentile", "百分位数"),
    ("stat_normalize", "数据归一化"),
    ("stat_standardize", "数据标准化"),
    ("random_password_generator", "随机密码生成"),
    ("url_encode_decode", "URL编解码"),
    ("md5_encrypt", "MD5加密"),
    ("sha_encrypt", "SHA加密"),
    ("timestamp_converter", "时间戳转换"),
    ("rgb_to_hsv", "RGB转HSV"),
    ("rgb_to_cmyk", "RGB转CMYK"),
    ("hex_to_cmyk", "HEX转CMYK"),
    ("uuid_generator", "UUID生成器"),
    ("regex_extract", "正则提取"),
    ("string_replace", "替换文本"),
    ("string_split", "分割文本"),
    ("string_join", "连接文本"),
    ("string_concat", "拼接文本"),
    ("string_trim", "去除空白"),
    ("string_case", "大小写"),
    ("string_substring", "截取文本"),
)


def node_catalog() -> list[dict[str, Any]]:
    return deepcopy(
        [
            {"moduleType": module_type, "title": title, "runnable": True}
            for module_type, title in _RUNNABLE_MODULES
        ]
    )


def runnable_module_types() -> frozenset[str]:
    return frozenset(module_type for module_type, _title in _RUNNABLE_MODULES)
