"""Generated Studio field metadata from WebRPA@5ccb900e8dcf1530aae66f676d87593c416c7ebb."""
# Source: reference/WebRPA/backend/app/services/ai_assistant_module_schemas.py (SHA-256 fdc519967c3e8405fb226f9c6831c057547d684bb7d187b51ee86b9a5628318e)
# Source: reference/WebRPA/backend/app/services/ai_assistant_module_schemas_autofix.py (SHA-256 0903b10421d4d96ad6ce7ed67d145c02c0bd70e61353e7e3ee81d8b7382c533a)
# License: reference/WebRPA/LICENSE; preserve original license and provenance.
# Adaptation: final source merge order, approved-scope filtering and explicit coverage.
# Regenerate: python3 scripts/export-studio-required-fields.py
from typing import Any

MODULE_REQUIRED_FIELDS: dict[str, Any] = {'schemaRevision': 'WebRPA@5ccb900e8dcf1530aae66f676d87593c416c7ebb',
 'coveredModules': ['ai_chat',
                    'ai_classify',
                    'ai_dedup_semantic',
                    'ai_element_selector',
                    'ai_extract',
                    'ai_generate_image',
                    'ai_generate_video',
                    'ai_normalize',
                    'ai_route',
                    'ai_sentiment',
                    'ai_smart_scraper',
                    'ai_summarize',
                    'ai_translate',
                    'ai_vision',
                    'ai_vision_act',
                    'allure_add_attachment',
                    'allure_add_step',
                    'allure_generate_report',
                    'allure_init',
                    'allure_start_test',
                    'allure_stop_test',
                    'api_request',
                    'api_trigger',
                    'assert_checkpoint',
                    'base64',
                    'break_loop',
                    'click_element',
                    'close_page',
                    'condition',
                    'continue_loop',
                    'csv_generate',
                    'csv_parse',
                    'dict_deep_copy',
                    'dict_filter',
                    'dict_flatten',
                    'dict_get',
                    'dict_get_path',
                    'dict_invert',
                    'dict_keys',
                    'dict_map_values',
                    'dict_merge',
                    'dict_operation',
                    'dict_sort',
                    'download_file',
                    'drag_element',
                    'element_change_trigger',
                    'element_exists',
                    'element_visible',
                    'email_trigger',
                    'export_log',
                    'extract_table_data',
                    'face_recognition',
                    'face_trigger',
                    'file_watcher_trigger',
                    'firecrawl_crawl',
                    'firecrawl_map',
                    'firecrawl_scrape',
                    'foreach',
                    'foreach_dict',
                    'gesture_trigger',
                    'get_child_elements',
                    'get_clipboard',
                    'get_element_info',
                    'get_sibling_elements',
                    'get_time',
                    'go_back',
                    'go_forward',
                    'group',
                    'handle_dialog',
                    'hex_to_cmyk',
                    'hotkey_trigger',
                    'hover_element',
                    'image_ocr',
                    'image_trigger',
                    'increment_decrement',
                    'infinite_loop',
                    'inject_javascript',
                    'input_prompt',
                    'input_text',
                    'js_script',
                    'json_parse',
                    'list_average',
                    'list_cartesian_product',
                    'list_chunk',
                    'list_count',
                    'list_difference',
                    'list_export',
                    'list_filter',
                    'list_find',
                    'list_flatten',
                    'list_get',
                    'list_intersection',
                    'list_length',
                    'list_map',
                    'list_max',
                    'list_merge',
                    'list_min',
                    'list_operation',
                    'list_remove_empty',
                    'list_reverse',
                    'list_sample',
                    'list_shuffle',
                    'list_slice',
                    'list_sort',
                    'list_sum',
                    'list_to_string_advanced',
                    'list_union',
                    'list_unique',
                    'lock_screen',
                    'loop',
                    'math_abs',
                    'math_base_convert',
                    'math_clamp',
                    'math_exp',
                    'math_factorial',
                    'math_floor',
                    'math_gcd',
                    'math_lcm',
                    'math_log',
                    'math_modulo',
                    'math_percentage',
                    'math_permutation',
                    'math_power',
                    'math_random_advanced',
                    'math_round',
                    'math_sqrt',
                    'math_trig',
                    'md5_encrypt',
                    'mouse_trigger',
                    'network_capture',
                    'network_monitor_start',
                    'network_monitor_stop',
                    'network_monitor_wait',
                    'note',
                    'notify_telegram',
                    'notify_webhook',
                    'ocr_captcha',
                    'open_page',
                    'page_load_complete',
                    'play_sound',
                    'print_log',
                    'printer_call',
                    'probability_trigger',
                    'python_script',
                    'random_number',
                    'random_password_generator',
                    'refresh_page',
                    'regex_extract',
                    'rgb_to_cmyk',
                    'rgb_to_hsv',
                    'run_command',
                    'run_workflow_file',
                    'save_image',
                    'scheduled_task',
                    'screenshot',
                    'scroll_page',
                    'select_dropdown',
                    'send_email',
                    'set_checkbox',
                    'set_clipboard',
                    'set_variable',
                    'sha_encrypt',
                    'share_file',
                    'share_folder',
                    'shutdown_system',
                    'slider_captcha',
                    'sound_trigger',
                    'ssh_connect',
                    'ssh_disconnect',
                    'ssh_download_file',
                    'ssh_execute_command',
                    'ssh_upload_file',
                    'start_screen_share',
                    'stat_median',
                    'stat_mode',
                    'stat_normalize',
                    'stat_percentile',
                    'stat_standardize',
                    'stat_stdev',
                    'stat_variance',
                    'stop_screen_share',
                    'stop_share',
                    'stop_workflow',
                    'string_case',
                    'string_concat',
                    'string_join',
                    'string_replace',
                    'string_split',
                    'string_substring',
                    'string_trim',
                    'subflow',
                    'switch_iframe',
                    'switch_tab',
                    'switch_to_main',
                    'system_notification',
                    'table_add_column',
                    'table_add_row',
                    'table_clear',
                    'table_delete_row',
                    'table_export',
                    'table_get_cell',
                    'table_set_cell',
                    'text_to_speech',
                    'timestamp_converter',
                    'upload_file',
                    'url_encode_decode',
                    'use_opened_page',
                    'uuid_generator',
                    'wait',
                    'wait_element',
                    'wait_page_load',
                    'webhook_request',
                    'webhook_trigger'],
 'requiredFields': {'ai_chat': ['userPrompt'],
                    'ai_classify': ['inputText', 'categories'],
                    'ai_dedup_semantic': ['inputList'],
                    'ai_element_selector': ['url'],
                    'ai_extract': ['inputText', 'fields'],
                    'ai_generate_image': ['prompt'],
                    'ai_generate_video': ['prompt'],
                    'ai_normalize': ['inputText'],
                    'ai_route': ['inputText', 'routes'],
                    'ai_sentiment': ['inputText'],
                    'ai_smart_scraper': ['url', 'prompt'],
                    'ai_summarize': ['inputText'],
                    'ai_translate': ['inputText'],
                    'ai_vision': ['userPrompt'],
                    'ai_vision_act': ['instruction'],
                    'allure_add_attachment': ['filePath'],
                    'allure_add_step': ['name'],
                    'allure_start_test': ['name'],
                    'api_request': ['requestUrl'],
                    'click_element': ['selector'],
                    'dict_deep_copy': ['dictVariable'],
                    'dict_filter': ['dictVariable'],
                    'dict_flatten': ['dictVariable'],
                    'dict_get': ['dictVariable'],
                    'dict_get_path': ['dictVariable', 'path'],
                    'dict_invert': ['dictVariable'],
                    'dict_keys': ['dictVariable'],
                    'dict_map_values': ['dictVariable'],
                    'dict_operation': ['dictVariable'],
                    'dict_sort': ['dictVariable'],
                    'download_file': ['downloadUrl'],
                    'drag_element': ['sourceSelector', 'targetSelector'],
                    'element_change_trigger': ['selector'],
                    'element_exists': ['selector'],
                    'element_visible': ['selector'],
                    'extract_table_data': ['tableSelector'],
                    'file_watcher_trigger': ['watchPath'],
                    'firecrawl_crawl': ['url'],
                    'firecrawl_map': ['url'],
                    'firecrawl_scrape': ['url'],
                    'foreach': ['listVariable'],
                    'foreach_dict': ['dictVariable'],
                    'get_child_elements': ['parentSelector'],
                    'get_element_info': ['selector'],
                    'hotkey_trigger': ['hotkey'],
                    'hover_element': ['selector'],
                    'image_ocr': ['imagePath'],
                    'image_trigger': ['imagePath'],
                    'increment_decrement': ['variableName'],
                    'inject_javascript': ['javascriptCode'],
                    'input_prompt': ['variableName'],
                    'input_text': ['selector', 'text'],
                    'js_script': ['code'],
                    'json_parse': ['sourceVariable'],
                    'list_average': ['listVariable'],
                    'list_chunk': ['listVariable'],
                    'list_count': ['listVariable'],
                    'list_export': ['listVariable'],
                    'list_filter': ['listVariable'],
                    'list_find': ['listVariable'],
                    'list_flatten': ['listVariable'],
                    'list_get': ['listVariable'],
                    'list_length': ['listVariable'],
                    'list_map': ['listVariable'],
                    'list_max': ['listVariable'],
                    'list_min': ['listVariable'],
                    'list_operation': ['listVariable'],
                    'list_remove_empty': ['listVariable'],
                    'list_reverse': ['listVariable'],
                    'list_sample': ['listVariable'],
                    'list_shuffle': ['listVariable'],
                    'list_slice': ['listVariable'],
                    'list_sort': ['listVariable'],
                    'list_sum': ['listVariable'],
                    'list_to_string_advanced': ['listVariable'],
                    'list_unique': ['listVariable'],
                    'math_base_convert': ['fromBase', 'toBase'],
                    'math_permutation': ['n', 'r'],
                    'math_power': ['base', 'exponent'],
                    'notify_telegram': ['botToken', 'chatId'],
                    'open_page': ['url'],
                    'print_log': ['logMessage'],
                    'printer_call': ['filePath'],
                    'python_script': ['scriptContent'],
                    'regex_extract': ['inputText', 'pattern'],
                    'run_command': ['command'],
                    'save_image': ['selector', 'savePath'],
                    'select_dropdown': ['selector'],
                    'send_email': ['recipientEmail', 'emailSubject', 'emailContent'],
                    'set_checkbox': ['selector'],
                    'set_clipboard': ['textContent'],
                    'set_variable': ['variableName', 'variableValue'],
                    'share_file': ['filePath'],
                    'share_folder': ['folderPath'],
                    'slider_captcha': ['sliderSelector'],
                    'ssh_connect': ['host', 'username', 'password'],
                    'ssh_download_file': ['remotePath', 'localPath'],
                    'ssh_execute_command': ['command'],
                    'ssh_upload_file': ['localPath', 'remotePath'],
                    'stat_median': ['listVariable'],
                    'stat_mode': ['listVariable'],
                    'stat_normalize': ['listVariable'],
                    'stat_percentile': ['listVariable', 'percentile'],
                    'stat_standardize': ['listVariable'],
                    'stat_stdev': ['listVariable'],
                    'stat_variance': ['listVariable'],
                    'string_concat': ['string1', 'string2'],
                    'string_join': ['listVariable', 'separator'],
                    'string_replace': ['inputText', 'searchValue', 'replaceValue'],
                    'string_split': ['inputText', 'separator'],
                    'subflow': ['subflowName'],
                    'system_notification': ['notifyTitle', 'notifyMessage'],
                    'text_to_speech': ['text'],
                    'upload_file': ['selector', 'filePath'],
                    'wait_element': ['selector'],
                    'webhook_request': ['url']},
 'conditionalRequired': {'wait': {'field': 'waitType',
                                  'default': 'time',
                                  'map': {'time': [], 'selector': ['selector'], 'navigation': []}}},
 'fieldLabels': {'ai_chat': {'userPrompt': '用户提示词，可用 {var} 引用',
                             'systemPrompt': '系统提示词（角色设定）',
                             'apiUrl/apiKey/model': '通常已在全局配置预填，留空即可',
                             'variableName': '保存 AI 回复的变量'},
                 'ai_classify': {'inputText': '待分类文本',
                                 'categories': '候选类别，逗号分隔(≥2个)',
                                 'variableName': '存储命中的类别名'},
                 'ai_dedup_semantic': {'inputList': '待去重列表(数组变量或JSON数组,≤300项)',
                                       'variableName': '存储去重后数组'},
                 'ai_extract': {'inputText': '待抽取文本（支持{变量}）',
                                'fields': '要抽取的字段：逗号分隔或JSON描述',
                                'variableName': '存储抽取出的JSON对象'},
                 'ai_generate_image': {'prompt': '图片描述'},
                 'ai_normalize': {'inputText': '待规整的杂乱值',
                                  'normalizeType': 'date/money/phone/number/name/address',
                                  'targetFormat': '自定义目标格式(可选)'},
                 'ai_route': {'inputText': '待判断内容',
                              'routes': '分支选项：每行 名称:说明，或JSON {名称:说明}',
                              'variableName': '存储命中的分支名'},
                 'ai_sentiment': {'inputText': '待分析文本',
                                  'variableName': '存储 {sentiment,score,confidence,reason}'},
                 'ai_smart_scraper': {'prompt': '对网页内容的提问/抓取目标'},
                 'ai_summarize': {'inputText': '待摘要长文本',
                                  'maxWords': '摘要最大字数',
                                  'style': '风格(可选,如 要点列表/一句话)'},
                 'ai_translate': {'inputText': '待翻译文本', 'targetLang': '目标语言，如 英文/日文/中文'},
                 'ai_vision': {'imageSource': 'element/screenshot/url/variable',
                               'imageSelector': 'imageSource=element 时填',
                               'imageUrl': 'imageSource=url 时填',
                               'imageVariable': 'imageSource=variable 时填',
                               'userPrompt': '对图片提问'},
                 'ai_vision_act': {'instruction': '自然语言描述要操作的屏幕目标，如：右上角的登录按钮',
                                   'action': 'click(单击)/double(双击)/right(右键)/move(仅移动)/locate(仅定位返回坐标)',
                                   'button': 'action=click/double 时的鼠标按键：left/right/middle',
                                   'variableName': '存储定位坐标 {x,y}'},
                 'allure_add_step': {'name': '步骤名称（历史别名 stepName 仍可用，新工作流请用 name）',
                                     'status': '步骤结果，取值：passed / failed / skipped / broken'},
                 'allure_start_test': {'name': '测试用例名称（历史别名 testName 仍可用，新工作流请用 name）',
                                       'severity': '严重级别，取值：blocker / critical / normal / minor / '
                                                   'trivial'},
                 'api_request': {'requestUrl': '请求 URL,支持 {var}',
                                 'requestMethod': 'GET / POST / PUT / DELETE / PATCH',
                                 'requestHeaders': '请求头(JSON 对象字符串,如 {"Authorization":"Bearer '
                                                   'xxx"})',
                                 'requestBody': '请求体(JSON 字符串或表单字符串)',
                                 'variableName': '响应 JSON 存到这个变量(后续 json_parse 解析)'},
                 'assert_checkpoint': {'checkType': 'variable(变量比较)/element(页面元素)/expression(表达式真值)',
                                       'operator': 'checkType=variable '
                                                   '时：==/!=/contains/not_contains/startswith/endswith/matches/>/</>=/<=/isEmpty/isNotEmpty',
                                       'actualValue': 'checkType=variable 的实际值（可用 {变量}）',
                                       'expectedValue': 'checkType=variable 的期望值',
                                       'selector': 'checkType=element 的元素选择器',
                                       'elementCheck': 'checkType=element '
                                                       '时：exists/not_exists/visible/hidden/text_contains/text_equals',
                                       'expectedText': 'elementCheck 为文本检查时的期望文本',
                                       'expression': 'checkType=expression 的表达式（解析后判断真值）',
                                       'onFail': '失败处理：stop(中断)/warn(警告继续)/continue(静默跳过)',
                                       'variableName': '存储断言结果布尔值'},
                 'base64': {'operation': 'encode/decode'},
                 'click_element': {'selector': 'CSS 选择器或 XPath，例如 #search-btn 或 .submit',
                                   'timeout': '等待元素出现的超时（秒）',
                                   'doubleClick': '是否双击',
                                   'followNewTab': '点击后若打开了新标签页，是否自动切换到新标签页继续操作（默认 '
                                                   'false；点链接开新标签页的场景应设为 true，否则后续模块仍在原页面上找元素）'},
                 'condition': {'operator': 'equals/not_equals/greater/less/contains/starts_with/ends_with/regex_match/is_empty/is_not_empty',
                               'leftValue': '左值（可用变量 {var}）',
                               'rightValue': '右值'},
                 'dict_get': {'defaultValue': 'key 不存在时返回的兜底值'},
                 'dict_get_path': {'path': '点路径，如 user.address.city'},
                 'dict_operation': {'dictVariable': '目标字典的变量名',
                                    'dictAction': 'set(写入键) / delete(删除键) / clear(清空)',
                                    'dictKey': '键名',
                                    'dictValue': '值(set 用)'},
                 'dict_sort': {'sortBy': 'key/value'},
                 'download_file': {'downloadUrl': '下载 URL',
                                   'downloadMode': 'url(直接下载) / trigger(点击触发下载)',
                                   'savePath': '保存目录',
                                   'fileName': '保存文件名(可空,自动从 URL 取)',
                                   'triggerSelector': 'trigger 模式下的触发按钮选择器',
                                   'variableName': '下载完成后的本地路径存到此变量'},
                 'drag_element': {'sourceSelector': '起点元素', 'targetSelector': '终点元素'},
                 'element_change_trigger': {'selector': '监控的父元素 selector'},
                 'extract_table_data': {'tableSelector': '表格的 CSS/XPath 选择器(例如 table.data-table)',
                                        'headerRow': '表头所在行号(1-based)',
                                        'exportToExcel': 'True 自动导出到 Excel 文件',
                                        'excelPath': '导出路径',
                                        'variableName': '表格数据存到此变量'},
                 'face_trigger': {'cameraIndex': '摄像头索引'},
                 'file_watcher_trigger': {'watchPath': '监控的文件夹'},
                 'foreach': {'listVariable': '要遍历的变量名（不带 {}）',
                             'itemVariable': '当前项变量名',
                             'indexVariable': '当前索引变量名'},
                 'foreach_dict': {'dictVariable': '字典变量名',
                                  'keyVariable': '键变量',
                                  'valueVariable': '值变量'},
                 'gesture_trigger': {'timeout': '超时毫秒'},
                 'get_child_elements': {'parentSelector': '父元素 selector',
                                        'childSelector': '可选：进一步过滤子元素的 selector'},
                 'get_element_info': {'selector': '目标元素选择器',
                                      'attribute': 'text(默认)/value/href/src/innerHTML/data-xxx '
                                                   '等任意属性',
                                      'variableName': '结果变量'},
                 'get_time': {'variableName': '结果变量'},
                 'handle_dialog': {'dialogAction': 'accept(确定) / dismiss(取消) / prompt(填值后确定)',
                                   'promptText': 'prompt 模式下要填入的文本',
                                   'saveMessage': 'True 把弹窗 message 存到此变量名'},
                 'hotkey_trigger': {'hotkey': '快捷键组合，如 Ctrl+Shift+A'},
                 'hover_element': {'selector': 'CSS / XPath 选择器', 'timeout': '等待超时秒'},
                 'image_trigger': {'imagePath': '目标图片'},
                 'increment_decrement': {'operation': 'increment/decrement', 'step': '步长'},
                 'inject_javascript': {'javascriptCode': '要执行的 JS 代码字符串',
                                       'injectMode': 'current(当前页面) / url(指定 URL 的标签页) / '
                                                     'index(指定标签页索引)',
                                       'saveResult': 'True 把 JS return 的值存到 saveResult 指定的变量名'},
                 'input_prompt': {'variableName': '**必填**:输入值会存到这个变量名,后续节点用 {variableName} 引用',
                                  'promptTitle': '弹窗标题',
                                  'promptMessage': '弹窗正文(提示用户该输入什么)',
                                  'inputMode': 'single(单行) / multiline / number / integer / '
                                               'password / list / file / folder / checkbox / '
                                               'slider_int / slider_float / select_single / '
                                               'select_multiple',
                                  'defaultValue': '默认填入值',
                                  'minValue': '数字/滑动条模式下的最小值',
                                  'maxValue': '数字/滑动条模式下的最大值',
                                  'selectOptions': 'select_single/select_multiple 模式的选项数组'},
                 'input_text': {'selector': '输入框的 CSS / XPath 选择器', 'text': '要输入的文本，可用 {变量名} 引用变量'},
                 'js_script': {'code': 'JavaScript 代码（return 的值会保存到 resultVariable）'},
                 'json_parse': {'sourceVariable': 'JSON 字符串变量名(例如 api_response)',
                                'jsonPath': 'JSONPath 表达式,如 $.data.items 或 $.users[0].name',
                                'variableName': '解析结果变量名'},
                 'list_flatten': {'depth': '扁平层数'},
                 'list_get': {'listVariable': '列表变量'},
                 'list_length': {'listVariable': '列表变量'},
                 'list_operation': {'listVariable': '目标列表的变量名',
                                    'listAction': 'append(尾插) / prepend(头插) / pop(尾出) / shift(头出) '
                                                  '/ remove(按值移除) / clear',
                                    'listValue': '要插入/移除的值(append/prepend/remove 用)',
                                    'listIndex': '操作位置索引'},
                 'list_sum': {'listVariable': '数字列表变量名'},
                 'loop': {'loopType': 'count(固定次数)/while(条件循环)',
                          'loopCount': '循环次数',
                          'indexVariable': '当前索引变量名'},
                 'math_base_convert': {'fromBase': '源进制 2/8/10/16', 'toBase': '目标进制'},
                 'math_log': {'base': '底数 e/2/10/任意数字'},
                 'math_permutation': {'n': '总数', 'r': '选取数'},
                 'open_page': {'url': '要打开的网页 URL'},
                 'print_log': {'logMessage': "日志正文,可用 {var_name} 引用上游变量,例如 '阶乘 = "
                                             "{factorial_result}'",
                               'logLevel': 'info / warning / error / success / debug'},
                 'printer_call': {'printerName': '打印机名（不填用默认）'},
                 'probability_trigger': {'probability': '百分比 0-100，路径1 概率'},
                 'python_script': {'scriptContent': 'Python 代码字符串。**重要规则**:(1) 用户代码会被自动包装在 def '
                                                    '_user_script(): 函数里,所以使用 `return 值` 把结果回传给 '
                                                    'resultVariable;(2) 想读取上游工作流变量,**必须用 '
                                                    '`vars.变量名`**(例如 `vars.user_input` 而不是直接 '
                                                    '`user_input`);(3) 想写入工作流变量,直接 `vars.变量名 = '
                                                    '值`(脚本结束后整套 vars 会自动 sync 回工作流);',
                                   'resultVariable': '脚本 return 的值会写入这个工作流变量',
                                   'scriptMode': 'content(直接写代码) 或 file(从文件读取)',
                                   'useBuiltinPython': 'True 使用 AutoFlow 随包 Python；False 可通过 '
                                                       'pythonPath 指定已安装的 Python',
                                   'timeout': '超时秒数'},
                 'random_number': {'variableName': '结果变量'},
                 'regex_extract': {'inputText': '要匹配的文本(支持 {var})',
                                   'pattern': '正则表达式',
                                   'extractMode': 'first(取第一个) / all(全部匹配)',
                                   'variableName': '结果变量名'},
                 'run_command': {'command': '命令字符串', 'shell': '是否走 shell'},
                 'run_workflow_file': {'workflowId': '要运行的工作流 id（在下拉里选择）',
                                       'workflowPath': '工作流文件路径（用文件方式指定时填）',
                                       'waitComplete': '是否等待它执行完再继续',
                                       'collectVariables': '是否回收它产生的变量到当前工作流',
                                       'passVariables': '是否把当前变量传给它',
                                       'timeout': '超时秒数'},
                 'save_image': {'selector': '<img> 选择器', 'savePath': '保存绝对路径'},
                 'scheduled_task': {'scheduleType': 'interval/cron/specific'},
                 'screenshot': {'selector': '可选：只截某个元素', 'variableName': '保存截图路径到变量'},
                 'scroll_page': {'direction': 'up/down/left/right/top/bottom',
                                 'distance': '像素',
                                 'selector': '可选：滚动到指定元素'},
                 'select_dropdown': {'selector': '<select> 选择器', 'value': '按 value 选'},
                 'send_email': {'recipientEmail': '收件人邮箱(多个用逗号分隔)',
                                'emailSubject': '邮件主题',
                                'emailContent': '邮件正文(支持 HTML)',
                                'senderEmail': '发件人邮箱(留空用全局配置)',
                                'authCode': 'SMTP 授权码(留空用全局配置)'},
                 'set_checkbox': {'selector': '复选框选择器', 'checked': 'true=勾选，false=取消'},
                 'set_clipboard': {'textContent': '要写入剪贴板的文本(支持 {var})',
                                   'contentType': 'text(文本) / image(图片)',
                                   'imagePath': 'image 模式下的图片路径'},
                 'set_variable': {'variableName': '变量名(例如 user_name)',
                                  'variableValue': '变量值(支持字符串/数字/布尔/JSON 字面量,也支持 {var} 引用其它变量)'},
                 'shutdown_system': {'delay': '延迟秒数'},
                 'stat_percentile': {'percentile': '分位数 0-100'},
                 'string_concat': {'string1': '字符串 1', 'string2': '字符串 2'},
                 'string_join': {'listVariable': '列表变量名', 'separator': '连接符'},
                 'string_replace': {'inputText': '原文本',
                                    'searchValue': '要替换的内容',
                                    'replaceValue': '替换后的内容',
                                    'replaceAll': '是否替换所有匹配'},
                 'string_split': {'inputText': '原字符串',
                                  'separator': '分隔符,例如 , 或 \\n',
                                  'maxSplit': '最多分几段(0=不限)'},
                 'subflow': {'subflowName': '子流程名'},
                 'switch_iframe': {'locateBy': 'selector(选择器) / index(索引) / name(name 属性)',
                                   'iframeSelector': 'iframe 的 CSS/XPath 选择器',
                                   'iframeIndex': 'iframe 的索引(0-based)',
                                   'iframeName': 'iframe 的 name 属性'},
                 'switch_tab': {'index': '按索引切（0 是第一个标签）', 'urlMatch': '按 URL 包含切'},
                 'system_notification': {'notifyTitle': '通知标题',
                                         'notifyMessage': '通知正文',
                                         'duration': '显示秒数'},
                 'text_to_speech': {'rate': '语速 0.1-10', 'volume': '音量 0-1'},
                 'timestamp_converter': {'operation': 'to_timestamp / to_datetime'},
                 'upload_file': {'selector': '<input type=file> 选择器', 'filePath': '本地文件绝对路径'},
                 'url_encode_decode': {'operation': 'encode/decode'},
                 'wait': {'waitType': '等待类型：time=固定等待秒数 / selector=等待某元素出现或消失 / '
                                      'navigation=等待页面加载完成',
                          'duration': 'time 模式：等待秒数（数字，如 2 表示 2 秒）',
                          'selector': 'selector 模式：要等待的元素 CSS 选择器',
                          'state': 'selector 模式：visible(默认)/hidden/attached/detached'},
                 'wait_element': {'selector': '等待出现的元素选择器'},
                 'wait_page_load': {'timeout': '最大等待秒'},
                 'webhook_trigger': {'method': 'GET/POST', 'saveToVariable': '保存请求数据的变量'}}}
