// Remediation M2 R2-11. Mirrors unknown_config_keys in
// apps/backend/src/autoflow/application/workflows/config_schema.py; the schema is generated by
// `python -m autoflow.bootstrap.executor_schema_export` from what each executor actually reads.
import schema from '../generated/executor-config-keys.json'

type NodeSchema = { reads: string[]; panelOnly: string[]; editorDefaults: string[] }
export type UnknownNodeSettings = { nodeId: string; label: string; keys: string[] }

const nodes = schema.nodes as Record<string, NodeSchema>
const common = new Set(schema.commonKeys)
const canvasOnly = new Set(['group', 'note'])
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value)

export function unknownConfigKeys(data: Record<string, unknown>, moduleType: string): string[] {
  const known = nodes[moduleType]
  if (!known || canvasOnly.has(moduleType)) return []
  const config = isRecord(data.config) ? { ...data, ...data.config } : data
  const allowed = new Set([...known.reads, ...known.panelOnly, ...known.editorDefaults])
  return Object.keys(config).filter(key => !allowed.has(key) && !common.has(key)).sort()
}

export function findUnknownSettings(list: readonly { id: string; data?: unknown }[]): UnknownNodeSettings[] {
  return list.flatMap(node => {
    if (!isRecord(node.data)) return []
    const moduleType = String(node.data.moduleType ?? '')
    const keys = unknownConfigKeys(node.data, moduleType)
    return keys.length ? [{ nodeId: node.id, label: String(node.data.label || moduleType || node.id), keys }] : []
  })
}

export function describeUnknownSettings(found: UnknownNodeSettings[]): string {
  return `以下设置不会被运行读取，可能来自其他版本或其他节点类型：${found.map(item => `「${item.label}」${item.keys.join('、')}`).join('；')}`
}
