import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
vi.hoisted(() => {
  const data = new Map<string, string>()
  vi.stubGlobal('localStorage', { getItem: (key: string) => data.get(key) ?? null, setItem: (key: string, value: string) => data.set(key, value), removeItem: (key: string) => data.delete(key) })
})
import { AutoBrowserDialog } from '../components/AutoBrowserDialog'
import { browserApi, elementPickerApi, systemApi } from '../api'
const log = vi.fn()
beforeEach(() => {
  log.mockClear()
  vi.spyOn(browserApi, 'getStatus').mockResolvedValue({ success: true, data: { isOpen: true, pickerActive: true } })
  vi.spyOn(elementPickerApi, 'getSelected').mockResolvedValue({ success: true, data: { selected: false } })
  vi.spyOn(elementPickerApi, 'getSimilar').mockResolvedValue({ success: true, data: { selected: false } })
})
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.useRealTimers() })
it.each(['close', 'stop'])('keeps confirmed browser state when %s returns a cleanup error', async action => {
  const method = action === 'close' ? 'close' : 'stopPicker'
  vi.spyOn(browserApi, method).mockResolvedValue({ success: false, error: '清理失败，请重试' })
  render(<AutoBrowserDialog isOpen onClose={vi.fn()} onLog={log} />)
  await screen.findByRole('button', { name: '停止选择' })
  fireEvent.click(screen.getByRole('button', { name: action === 'close' ? '关闭浏览器' : '停止选择' }))
  await waitFor(() => expect(log).toHaveBeenCalledWith('error', expect.stringContaining('清理失败')))
  expect(screen.getByRole('button', { name: '关闭浏览器' })).toBeDefined()
  expect(screen.getByRole('button', { name: '停止选择' })).toBeDefined()
  expect(log.mock.calls.some(([, message]) => /已关闭|已停止/.test(message))).toBe(false)
})
it('keeps the last confirmed state on a failed refresh instead of claiming closure', async () => {
  render(<AutoBrowserDialog isOpen onClose={vi.fn()} onLog={log} />)
  await screen.findByRole('button', { name: '停止选择' })
  vi.mocked(browserApi.getStatus).mockRejectedValueOnce(new Error('offline'))
  fireEvent.click(screen.getByTitle('刷新状态'))
  await waitFor(() => expect(log).toHaveBeenCalledWith('error', expect.stringContaining('offline')))
  expect(screen.getByRole('button', { name: '关闭浏览器' })).toBeDefined()
  expect(screen.getByRole('button', { name: '停止选择' })).toBeDefined()
})
it.each(['close-panel', 'unmount'])('does not copy a late selected element after %s', async action => {
  vi.useFakeTimers()
  let release!: (value: Awaited<ReturnType<typeof elementPickerApi.getSelected>>) => void
  vi.mocked(elementPickerApi.getSelected).mockImplementation(() => new Promise(resolve => { release = resolve }))
  const copy = vi.spyOn(systemApi, 'setClipboard').mockResolvedValue({ success: true })
  const view = render(<AutoBrowserDialog isOpen onClose={vi.fn()} onLog={log} />)
  await act(async () => {})
  await act(async () => { vi.advanceTimersByTime(500) })
  expect(elementPickerApi.getSelected).toHaveBeenCalledOnce()
  if (action === 'unmount') view.unmount()
  else view.rerender(<AutoBrowserDialog isOpen={false} onClose={vi.fn()} onLog={log} />)
  await act(async () => release({ success: true, data: { selected: true, element: { selector: '#late' } } }))
  expect(copy).not.toHaveBeenCalled()
  expect(elementPickerApi.getSimilar).not.toHaveBeenCalled()
  expect(log).not.toHaveBeenCalled()
})
it('keeps at most one polling request in flight', async () => {
  vi.useFakeTimers()
  let release!: (value: Awaited<ReturnType<typeof elementPickerApi.getSelected>>) => void
  vi.mocked(elementPickerApi.getSelected).mockImplementation(() => new Promise(resolve => { release = resolve }))
  render(<AutoBrowserDialog isOpen onClose={vi.fn()} onLog={log} />)
  await act(async () => {})
  await act(async () => { vi.advanceTimersByTime(2500) })
  expect(elementPickerApi.getSelected).toHaveBeenCalledOnce()
  await act(async () => release({ success: true, data: { selected: false } }))
})
it('does not resurrect the picker from a refresh response older than a confirmed stop', async () => {
  render(<AutoBrowserDialog isOpen onClose={vi.fn()} onLog={log} />)
  await screen.findByRole('button', { name: '停止选择' })
  let release!: (value: Awaited<ReturnType<typeof browserApi.getStatus>>) => void
  vi.mocked(browserApi.getStatus).mockImplementationOnce(() => new Promise(resolve => { release = resolve }))
  vi.spyOn(browserApi, 'stopPicker').mockResolvedValue({ success: true })
  fireEvent.click(screen.getByTitle('刷新状态'))
  fireEvent.click(screen.getByRole('button', { name: '停止选择' }))
  await screen.findByRole('button', { name: '启动选择器' })
  await act(async () => release({ success: true, data: { isOpen: true, pickerActive: true } }))
  expect(screen.queryByRole('button', { name: '停止选择' })).toBeNull()
})
it('suppresses repeated polling errors without pretending the picker has stopped and recovers polling', async () => {
  vi.useFakeTimers()
  vi.mocked(elementPickerApi.getSelected).mockResolvedValue({ success: false, error: '暂时离线' })
  render(<AutoBrowserDialog isOpen onClose={vi.fn()} onLog={log} />)
  await act(async () => {})
  await act(async () => { vi.advanceTimersByTime(500) })
  await act(async () => { vi.advanceTimersByTime(500) })
  expect(log).toHaveBeenCalledTimes(1)
  expect(screen.getByRole('button', { name: '停止选择' })).toBeDefined()
  vi.mocked(elementPickerApi.getSelected).mockResolvedValueOnce({ success: true, data: { selected: false } })
  await act(async () => { vi.advanceTimersByTime(500) })
  await act(async () => { vi.advanceTimersByTime(500) })
  expect(log).toHaveBeenCalledTimes(2)
})
it('ignores a similar-element response after the panel closes', async () => {
  vi.useFakeTimers()
  let release!: (value: Awaited<ReturnType<typeof elementPickerApi.getSimilar>>) => void
  vi.mocked(elementPickerApi.getSimilar).mockImplementation(() => new Promise(resolve => { release = resolve }))
  const copy = vi.spyOn(systemApi, 'setClipboard').mockResolvedValue({ success: true })
  const view = render(<AutoBrowserDialog isOpen onClose={vi.fn()} onLog={log} />)
  await act(async () => {})
  await act(async () => { vi.advanceTimersByTime(500) })
  expect(elementPickerApi.getSimilar).toHaveBeenCalledOnce()
  view.rerender(<AutoBrowserDialog isOpen={false} onClose={vi.fn()} onLog={log} />)
  await act(async () => release({ success: true, data: { selected: true, similar: { pattern: '.row-{index}', count: 4, minIndex: 1, maxIndex: 4 } } }))
  expect(copy).not.toHaveBeenCalled()
  expect(log).not.toHaveBeenCalled()
})
it.each(['start','stop','navigate'] as const)('serializes %s with other browser commands and restores controls after rejection',async action=>{
 vi.mocked(browserApi.getStatus).mockResolvedValue({success:true,data:{isOpen:true,pickerActive:action==='stop'}})
 const method=action==='start'?'startPicker':action==='stop'?'stopPicker':'navigate'
 let release!:(value:{success:boolean;error?:string})=>void
 const command=vi.spyOn(browserApi,method).mockImplementation(()=>new Promise<{success:boolean;error?:string}>(resolve=>{release=resolve}))
 const close=vi.spyOn(browserApi,'close').mockResolvedValue({success:true})
 render(<AutoBrowserDialog isOpen onClose={vi.fn()} onLog={log}/>)
 await screen.findByRole('button',{name:'关闭浏览器'})
 if(action==='navigate')fireEvent.change(screen.getByPlaceholderText('https://example.com'),{target:{value:'https://example.test'}})
 const button=screen.getByRole('button',{name:action==='start'?'启动选择器':action==='stop'?'停止选择':'跳转'})
 fireEvent.click(button);fireEvent.click(button);fireEvent.click(screen.getByRole('button',{name:'关闭浏览器'}))
 expect(command).toHaveBeenCalledTimes(1)
 expect(close).not.toHaveBeenCalled()
 expect((button as HTMLButtonElement).disabled).toBe(true)
 await act(async()=>release({success:false,error:'命令被拒绝'}))
 expect((button as HTMLButtonElement).disabled).toBe(false)
 expect(log).toHaveBeenCalledWith('error',expect.stringContaining('命令被拒绝'))
})
