import { expect, it, vi } from 'vitest'
import { ApiClientError, type StreamingApiClient } from '../../shared/api/client'
import { DataCommandUncertain } from '../project-data/data-command'
import { createProjectRunsApi } from './api'
const client = (request: StreamingApiClient['request']): StreamingApiClient => ({ request, stream: vi.fn(), health: vi.fn() })
const batch = { batchId: 'b', projectId: 'p', automationId: 'a', startOperationId: 'op', status: 'accepted', statusRevision: 1, managementRevision: 1, requestedCount: 2, createdTaskCount: 0, activeTaskCount: 0, createdAt: '' }
it('uses scoped cancelable list URLs', async () => { const request = vi.fn().mockResolvedValue({ items: [], total: 0, page: 2, pageSize: 20, sort: '-createdAt' }), signal = new AbortController().signal; await createProjectRunsApi(client(request), 'p/x').listBatches({ automationId: 'a', status: 'running', page: 2, pageSize: 20, sort: '-createdAt' }, signal); expect(request).toHaveBeenCalledWith('/api/v1/projects/p%2Fx/batches?automationId=a&status=running&page=2&pageSize=20&sort=-createdAt', { signal }) })
it('looks up the original key after an unknown start and does not invent a new key', async () => { const request = vi.fn().mockRejectedValueOnce(new TypeError('offline')).mockResolvedValueOnce({ projectId: 'p', idempotencyKey: 'key', kind: 'startBatch', status: 'succeeded', resource: { type: 'batch', projectId: 'p', batchId: 'b' }, result: { batch } }); await expect(createProjectRunsApi(client(request), 'p').start('a', { expectedAutomationRevision: 1, parameters: {} }, 'key')).resolves.toEqual({ state: 'succeeded', batch }); expect(request.mock.calls[0][1].headers).toEqual({ 'Idempotency-Key': 'key' }); expect(request.mock.calls[1][0]).toContain('/operations/by-idempotency-key/key') })
it('resume lookup reports not accepted on 404 without resubmitting', async () => { const request = vi.fn().mockRejectedValue(new ApiClientError('missing', 404, 'OPERATION_NOT_FOUND')); await expect(createProjectRunsApi(client(request), 'p').resumeStop('b', { expectedStatusRevision: 2, reason: '用户停止' }, 'same', { retryIfNotAccepted: false })).rejects.toThrow('原操作尚未接受'); expect(request).toHaveBeenCalledTimes(1) })
it('returns a normally accepted running stop operation without treating it as unknown', async () => { const operation = { operationId: 'op', projectId: 'p', idempotencyKey: 'key', kind: 'stopBatch', status: 'running', statusRevision: 1, resource: { type: 'batch', projectId: 'p', batchId: 'b' }, result: null, error: null, inputs: [], capturedAt: '' }; const request = vi.fn().mockResolvedValue({ operation }); await expect(createProjectRunsApi(client(request), 'p').stop('b', { expectedStatusRevision: 2, reason: '用户停止' }, 'key')).resolves.toEqual({ state: 'accepted', operation }); expect(request).toHaveBeenCalledTimes(1) })
it('uses the force-stop route and operation kind with the caller key', async () => { const operation = { operationId: 'op', projectId: 'p', idempotencyKey: 'force-key', kind: 'forceStopBatch', status: 'running', statusRevision: 1, resource: { type: 'batch', projectId: 'p', batchId: 'b' }, result: null, error: null, inputs: [], capturedAt: '' }; const request = vi.fn().mockResolvedValue({ operation }); await expect(createProjectRunsApi(client(request), 'p').forceStop('b', { expectedStatusRevision: 2, reason: '强制停止' }, 'force-key')).resolves.toEqual({ state: 'accepted', operation }); expect(request).toHaveBeenCalledWith('/api/v1/projects/p/batches/b/force-stop', expect.objectContaining({ headers: { 'Idempotency-Key': 'force-key' } })) })
it('rejects non-finite request values before sending', async () => { const request = vi.fn(); await expect(createProjectRunsApi(client(request), 'p').start('a', { expectedAutomationRevision: 1, parameters: { bad: Number.NaN } }, 'key')).rejects.toThrow(); expect(request).not.toHaveBeenCalled() })
it('posts a follow-up batch under the task and accepts the batch the operation created', async () => { const operation = { operationId: 'op', projectId: 'p', idempotencyKey: 'fk', kind: 'followUpBatch', status: 'succeeded', statusRevision: 2, resource: { type: 'batch', projectId: 'p', batchId: 'b2' }, result: { batch: { ...batch, batchId: 'b2' } }, error: null, inputs: [], capturedAt: '' }, request = vi.fn().mockResolvedValue({ operation }); await expect(createProjectRunsApi(client(request), 'p').followUp('t1', { mode: 'originalInputGroup', expectedTaskStatusRevision: 3 }, 'fk')).resolves.toEqual({ state: 'succeeded', batch: { ...batch, batchId: 'b2' } }); expect(request).toHaveBeenCalledWith('/api/v1/projects/p/tasks/t1/follow-up-batches', expect.objectContaining({ method: 'POST', headers: { 'Idempotency-Key': 'fk' }, body: { mode: 'originalInputGroup', expectedTaskStatusRevision: 3 } })) })
it('never accepts a follow-up batch whose identity does not match the operation resource', async () => { const mismatch = { operationId: 'op', projectId: 'p', idempotencyKey: 'fk', kind: 'followUpBatch', status: 'succeeded', statusRevision: 2, resource: { type: 'batch', projectId: 'p', batchId: 'b2' }, result: { batch: { ...batch, batchId: 'b3' } }, error: null, inputs: [], capturedAt: '' }, request = vi.fn().mockResolvedValue({ operation: mismatch }); await expect(createProjectRunsApi(client(request), 'p').followUp('t1', { mode: 'originalInputGroup', expectedTaskStatusRevision: 3 }, 'fk')).rejects.toBeInstanceOf(DataCommandUncertain) })
