import { AlertDialog, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogTitle } from '../../../shared/components/ui/alert-dialog'
import { Button } from '../../../shared/components/ui/button'
import { Input } from '../../../shared/components/ui/input'
import { Textarea } from '../../../shared/components/ui/textarea'
import { useState } from 'react'
import { presentRunFailure } from '../presentation'
export function StopBatchDialog({ open, force = false, busy, error, automationName, startedAt, activeTaskCount, onOpenChange, onConfirm }: { open: boolean; force?: boolean; busy: boolean; error?: string; automationName: string; startedAt: string; activeTaskCount: number; onOpenChange(open: boolean): void; onConfirm(reason: string): void }) {
  const [reason, setReason] = useState('')
  const [confirmation, setConfirmation] = useState('')
  const canConfirm = !force || confirmation === '强制停止'
  return <AlertDialog open={open} onOpenChange={value => { if (!busy) onOpenChange(value) }}><AlertDialogContent onEscapeKeyDown={event => { if (busy) event.preventDefault() }}><AlertDialogTitle>{force ? '强制停止批次？' : '停止当前批次？'}</AlertDialogTitle><AlertDialogDescription>{force ? '仅当正常停止未能完成时使用。系统将撤销旧执行权限并清理进程；无法确认的外部结果会保留为待核验，不会自动重跑网页。' : '停止创建后续执行，通知正在运行的任务结束并清理环境。已经提交的记录和执行结果会保留。'}</AlertDialogDescription><dl className="grid grid-cols-3 gap-3 rounded-control border border-line bg-subtle p-3 text-sm"><div className="col-span-3"><dt className="text-muted">自动化</dt><dd className="m-0 break-words font-medium">{automationName}</dd></div><div className="col-span-2"><dt className="text-muted">开始时间</dt><dd className="m-0">{new Date(startedAt).toLocaleString('zh-CN', { hour12: false })}</dd></div><div><dt className="text-muted">活动任务</dt><dd className="m-0">{activeTaskCount}</dd></div></dl>{force ? <label className="grid gap-2 text-sm">输入“强制停止”以确认<Input aria-label="确认强制停止" value={confirmation} disabled={busy} spellCheck={false} placeholder="强制停止" onChange={event => setConfirmation(event.target.value)}/></label> : null}<label className="grid gap-2 text-sm">停止原因<Textarea aria-label="停止原因" value={reason} maxLength={500} disabled={busy} placeholder="可选，便于后续核对" onChange={event => setReason(event.target.value)}/></label>{error ? <p role="alert" className="text-sm text-danger">{presentRunFailure(error)}</p> : null}<div className="flex justify-end gap-2"><AlertDialogCancel asChild><Button disabled={busy}>取消</Button></AlertDialogCancel><Button variant="danger" loading={busy} disabled={busy || !canConfirm} onClick={() => onConfirm(reason.trim() || (force ? '用户在管理页面强制停止批次' : '用户在管理页面停止批次'))}>{force ? '确认强制停止' : '确认停止'}</Button></div></AlertDialogContent></AlertDialog>
}
