import { ArrowRight, ListBullets, MagnifyingGlass, X } from '@phosphor-icons/react'
import { FormEvent, ReactNode, useEffect, useState } from 'react'
import type { components } from '../../../shared/api/generated'
import { Button } from '../../../shared/components/ui/button'
import { Input } from '../../../shared/components/ui/input'
import { Pagination } from '../../../shared/components/ui/pagination'
import { Select } from '../../../shared/components/ui/select'
import { Skeleton } from '../../../shared/components/ui/skeleton'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow, TableScroll } from '../../../shared/components/ui/table'
import { TableStatus } from '../../../shared/components/ui/table-status'
import { TableToolbar } from '../../../shared/components/ui/table-toolbar'
import { presentRunFailure } from '../presentation'

type TaskPage = components['schemas']['TaskPage']; type Task = components['schemas']['TaskView']
export type TaskFilters = { q: string | null; batchId: string | null; status: string | null; period: string | null }
export type TaskDirectoryProps = { page?: TaskPage; filters: TaskFilters; batchOptions?: { id: string; name: string }[]; context?: 'directory' | 'batch' | 'frozen'; loading?: boolean; refreshing?: boolean; error?: unknown; footerNote?: ReactNode; onFiltersChange(value: TaskFilters): void; onPageChange(page: number): void; onOpen(task: Task): void; onOpenManual?(task: Task): void; onRetry(): void }
const statuses = [{ value: '', label: '全部状态' }, { value: 'queued', label: '排队中' }, { value: 'running', label: '运行中' }, { value: 'waiting_manual', label: '等待人工' }, { value: 'resume_queued', label: '等待恢复' }, { value: 'finishing', label: '正在结束' }, { value: 'stopping', label: '正在停止' }, { value: 'reconciling', label: '正在核对' }, { value: 'succeeded', label: '成功' }, { value: 'failed', label: '失败' }, { value: 'cancelled', label: '已取消' }, { value: 'timed_out', label: '已超时' }, { value: 'interrupted', label: '已中断' }]
const statusLabel = (value: string) => statuses.find(item => item.value === value)?.label ?? value
const tone = (value: string) => value === 'succeeded' ? 'success' : ['failed', 'timed_out', 'interrupted'].includes(value) ? 'danger' : ['waiting_manual', 'stopping'].includes(value) ? 'warning' : 'neutral'
const taskName = (task: Task) => `任务 ${task.taskOrdinal}`
/** 终态但服务端没有记录结束节点时留 `—`，不得把"没有事实"写成"尚未结束"。 */
const endNode = (task: Task) => task.endNodeName ?? (['succeeded', 'failed', 'cancelled', 'timed_out', 'interrupted'].includes(task.status) ? '—' : '尚未结束')
/** 最近状态时间来自服务端事实；缺少事实时留空，不按客户端时钟推断。 */
const lastStatusAt = (task: Task) => task.lastStatusAt ?? null
export function TaskDirectory({ page, filters, batchOptions = [], context = 'directory', loading = false, refreshing = false, error, footerNote, onFiltersChange, onPageChange, onOpen, onOpenManual, onRetry }: TaskDirectoryProps) {
  const frozen = context === 'frozen'
  const [search, setSearch] = useState(filters.q ?? '')
  useEffect(() => setSearch(filters.q ?? ''), [filters.q])
  const submit = (event: FormEvent) => { event.preventDefault(); const q = search.trim(); if (q !== (filters.q ?? '')) onFiltersChange({ ...filters, q: q || null }) }
  const filtered = Boolean(filters.q || filters.batchId || filters.status || filters.period)
  const optionName = (batchId: string) => batchOptions.find(item => item.id === batchId)?.name
  const automationName = (task: Task) => task.automationName ?? optionName(task.batchId)?.split(' · ')[0] ?? '自动化'
  const batchLabel = (task: Task) => optionName(task.batchId) ?? (task.batchStartedAt ? `${automationName(task)} · ${new Date(task.batchStartedAt).toLocaleString('zh-CN')}` : '—')
  const batchChoices = filters.batchId && !batchOptions.some(item => item.id === filters.batchId)
    ? [{ value: filters.batchId, label: '批次资料暂不可用' }, ...batchOptions.map(item => ({ value: item.id, label: item.name }))]
    : batchOptions.map(item => ({ value: item.id, label: item.name }))
  return <section className="grid gap-4">{frozen ? null : <TableToolbar label="任务筛选" className="flex flex-wrap justify-end gap-3"><form role="search" className="flex min-w-64 flex-1 gap-2" onSubmit={submit}><Input aria-label="搜索任务" value={search} maxLength={120} placeholder="搜索自动化名称或输入内容" disabled={refreshing} onChange={event => setSearch(event.target.value)}/>{filters.q ? <Button type="button" variant="ghost" aria-label="清除任务搜索" disabled={refreshing} onClick={() => { setSearch(''); onFiltersChange({ ...filters, q: null }) }}><X aria-hidden/></Button> : null}<Button type="submit" aria-label="执行任务搜索" disabled={refreshing || search.trim() === (filters.q ?? '')}><MagnifyingGlass aria-hidden/></Button></form><Select aria-label="批次筛选" className="w-48" clearable={false} value={filters.batchId ?? ''} options={[{ value: '', label: '全部批次' }, ...batchChoices]} disabled={refreshing} onValueChange={value => onFiltersChange({ ...filters, batchId: value || null })}/><Select aria-label="任务状态筛选" className="w-40" clearable={false} value={filters.status ?? ''} options={statuses} disabled={refreshing} onValueChange={value => onFiltersChange({ ...filters, status: value || null })}/><Select aria-label="任务时间筛选" className="w-32" clearable={false} value={filters.period ?? ''} options={[{ value: '', label: '全部时间' }, { value: '7d', label: '近 7 天' }, { value: '30d', label: '近 30 天' }]} disabled={refreshing} onValueChange={value => onFiltersChange({ ...filters, period: value || null })}/></TableToolbar>}
    {error ? <div role="alert" className="flex items-center justify-between rounded-control border border-warning/30 bg-warning/10 p-3"><span>{page ? `刷新失败，当前显示上次读取的任务：${presentRunFailure(error)}` : `任务读取失败：${presentRunFailure(error)}`}</span><Button onClick={onRetry}>重试读取</Button></div> : null}
    {loading && !page ? <div role="status" aria-label="正在加载任务" className="grid gap-2">{[1, 2, 3].map(item => <Skeleton key={item} className="h-16"/>)}</div> : page?.items.length ? <TableScroll label="任务目录" className="rounded-control border border-line bg-surface"><Table><TableHeader><TableRow><TableHead>任务 / 自动化</TableHead>{context === 'batch' ? <><TableHead>输入标识</TableHead><TableHead>任务状态</TableHead><TableHead>结束节点</TableHead><TableHead>结束时间</TableHead></> : context === 'frozen' ? <><TableHead>所属批次</TableHead><TableHead>输入标识</TableHead><TableHead>任务状态</TableHead><TableHead>任务结束时间</TableHead></> : <><TableHead>所属批次</TableHead><TableHead>输入标识</TableHead><TableHead>任务状态</TableHead><TableHead>当前或结束节点</TableHead><TableHead>时间<span className="block text-xs font-normal text-muted">最近状态时间</span></TableHead></>}<TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{page.items.map(task => <TableRow key={task.taskId}><TableCell><strong>{taskName(task)}</strong>{context === 'batch' ? null : <span className="block text-xs text-muted">{automationName(task)}</span>}</TableCell>{context === 'batch' ? <><TableCell>{task.inputIdentifier ?? '参数任务'}</TableCell><TableCell><TableStatus tone={tone(task.status)}>{statusLabel(task.status)}</TableStatus></TableCell><TableCell>{endNode(task)}</TableCell><TableCell>{task.completedAt ? <time dateTime={task.completedAt}>{new Date(task.completedAt).toLocaleString('zh-CN')}</time> : '—'}</TableCell></> : <><TableCell>{batchLabel(task)}</TableCell><TableCell>{task.inputIdentifier ?? '参数任务'}</TableCell><TableCell><TableStatus tone={tone(task.status)}>{statusLabel(task.status)}</TableStatus></TableCell>{frozen ? null : <><TableCell>{endNode(task)}</TableCell><TableCell>{lastStatusAt(task) ? <time dateTime={lastStatusAt(task)!}>{new Date(lastStatusAt(task)!).toLocaleString('zh-CN')}</time> : '—'}</TableCell></>}{frozen ? <TableCell>{task.completedAt ? <time dateTime={task.completedAt}>{new Date(task.completedAt).toLocaleString('zh-CN')}</time> : '—'}</TableCell> : null}</>}<TableCell>{task.manualItemId && onOpenManual ? <Button variant="ghost" className="text-clay" onClick={() => onOpenManual(task)}>查看事项<ArrowRight aria-hidden/></Button> : <Button variant="ghost" className="text-clay" onClick={() => onOpen(task)}>{frozen ? '查看日志' : '查看任务'}<ArrowRight aria-hidden/></Button>}</TableCell></TableRow>)}</TableBody></Table></TableScroll> : !error ? <div className="grid min-h-72 place-items-center text-center"><div><ListBullets size={52} className="mx-auto text-muted"/><h3>{frozen ? '该结果集内没有符合条件的任务' : filtered ? '没有匹配的任务' : '还没有任务记录'}</h3><p className="text-muted">{frozen ? '统计快照是冻结的，不会随当前筛选变化。' : filtered ? '调整搜索或筛选条件后再试。' : '批次创建任务后会显示在这里。'}</p>{filtered && !frozen ? <Button onClick={() => { setSearch(''); onFiltersChange({ q: null, batchId: null, status: null, period: null }) }}>清除筛选</Button> : null}</div></div> : null}
    {footerNote}
    {page ? <Pagination showPage offset={(page.page - 1) * page.pageSize} limit={page.pageSize} total={page.total} count={page.items.length} disabled={refreshing} onOffsetChange={offset => onPageChange(Math.floor(offset / page.pageSize) + 1)}/> : null}</section>
}
