// Source: WebRPA@5ccb900e, components/workflow/documentation/documents.ts; see SOURCE.md for license and adaptation boundaries.
import {
  Rocket,
  Zap,
  Database,
  Brain,
  Settings2,
  BookOpen,
  Target,
  Workflow,
  Globe,
  Variable,
  Bug,
  Bell,
  Webhook,
  ClipboardCheck,
  Share2,
  Terminal,
  Wrench,
  Eye,
  Network,
  Calculator,
  Clock,
  Puzzle,
  Bot,
} from 'lucide-react'
import type { DocumentItem } from './types'

export const documents: DocumentItem[] = [
  {
    id: 'getting-started',
    title: '快速入门',
    icon: Rocket,
    description: '创建、配置和保存第一个流程',
  },
  {
    id: 'ai-assistant-guide',
    title: 'AI 小助手指南',
    icon: Bot,
    description: 'AI 面板、画布操作与权限确认',
  },
  {
    id: 'browser-guide',
    title: '自动化浏览器',
    icon: Globe,
    description: '浏览器原理与元素选择器',
  },
  {
    id: 'basic-modules',
    title: '基础模块详解',
    icon: Zap,
    description: '浏览器操作、表单填写、数据采集等',
  },
  {
    id: 'module-reference',
    title: '模块速查表',
    icon: BookOpen,
    description: '按保留分类查找动作与用途',
  },
  {
    id: 'variables-guide',
    title: '变量系统详解',
    icon: Variable,
    description: '变量类型、引用、列表字典',
  },
  {
    id: 'data-processing',
    title: '数据处理指南',
    icon: Database,
    description: '变量、列表、字典、字符串操作',
  },
  {
    id: 'math-flow-guide',
    title: '数学统计与CSV',
    icon: Calculator,
    description: '数学运算、统计分析、CSV处理、概率触发器',
  },
  {
    id: 'network-guide',
    title: '网络请求与抓包',
    icon: Network,
    description: 'HTTP请求、发送邮件、Webhook、网络抓包',
  },
  {
    id: 'triggers-guide',
    title: '触发器使用指南',
    icon: Webhook,
    description: 'Webhook、热键、文件监控、邮件、API触发',
  },
  {
    id: 'scheduled-tasks-guide',
    title: '计划任务系统',
    icon: Clock,
    description: '定时执行、重复任务、任务管理',
  },
  {
    id: 'custom-modules-guide',
    title: '自定义模块',
    icon: Puzzle,
    description: '创建和管理自定义模块，扩展功能',
  },
  {
    id: 'platform-guide',
    title: '平台能力',
    icon: Wrench,
    description: '导出、凭据和远程存储配置',
  },
  {
    id: 'advanced-features',
    title: '高级功能',
    icon: Brain,
    description: 'AI对话、流程控制、子流程、脚本',
  },
  {
    id: 'ai-vision-guide',
    title: 'AI识别与爬虫',
    icon: Eye,
    description: 'OCR、验证码、人脸识别、AI智能爬虫',
  },
  {
    id: 'notify-guide',
    title: '多渠道通知',
    icon: Bell,
    description: '钉钉、微信、Telegram、Discord等16种通知',
  },
  {
    id: 'ssh-guide',
    title: 'SSH 远程操作',
    icon: Terminal,
    description: 'SSH连接服务器、执行命令、上传下载文件',
  },
  {
    id: 'share-guide',
    title: '网络与屏幕共享',
    icon: Share2,
    description: '局域网文件共享、屏幕实时投屏',
  },
  {
    id: 'utils-guide',
    title: '实用工具',
    icon: Wrench,
    description: '加密哈希、随机生成、颜色转换、打印',
  },
  {
    id: 'test-report-guide',
    title: '测试报告指南',
    icon: ClipboardCheck,
    description: 'Allure测试报告生成与管理',
  },
  {
    id: 'selector-guide',
    title: '选择器完全指南',
    icon: Target,
    description: 'CSS 与 XPath 选择器从入门到精通',
  },
  {
    id: 'notifications-guide',
    title: '消息通知与交互',
    icon: Bell,
    description: '日志、提示音、语音播报、用户输入',
  },
  {
    id: 'debug-guide',
    title: '调试与错误处理',
    icon: Bug,
    description: '调试技巧与性能优化',
  },
  {
    id: 'practical-cases',
    title: '实战案例',
    icon: BookOpen,
    description: '常见场景的完整解决方案',
  },
  {
    id: 'workflow-patterns',
    title: '工作流模式',
    icon: Workflow,
    description: '常用设计模式和最佳实践',
  },
  {
    id: 'tips-tricks',
    title: '技巧与窍门',
    icon: Settings2,
    description: '让你的工作流更高效',
  },
]
