from collections.abc import Sequence
from datetime import datetime
from typing import Protocol, Self

from .models import Connection, Health, Projection, ProviderPage, ProxyGroup


class ProxyPanelProvider(Protocol):
    async def verify(self, api_key: bytes) -> ProviderPage: ...
    async def list_proxies(self, api_key: bytes) -> ProviderPage: ...


class ProxyHealthProbe(Protocol):
    async def probe(self, projection: Projection) -> Health: ...


class ProxyRepository(Protocol):
    def add_connection(self, connection: Connection) -> None: ...
    def get_connection(self, connection_id: str) -> Connection | None: ...
    def list_connections(self) -> list[Connection]: ...
    def save_connection(
        self, connection: Connection, expected_revision: int, expected_generation: int
    ) -> None: ...
    def mark_connection_verified(self, connection_id: str, secret_ref: str, verified_at: datetime) -> Connection: ...
    def fail_verification(
        self, connection_id: str, secret_ref: str, error: dict, failed_at: datetime
    ) -> None: ...
    def begin_sync(
        self,
        connection_id: str,
        secret_ref: str,
        expected_generation: int,
        sync_token: str,
        started_at: datetime,
    ) -> Connection: ...
    def validate_sync(
        self, connection_id: str, secret_ref: str, generation: int, sync_token: str
    ) -> Connection: ...
    def complete_sync(
        self, connection_id: str, generation: int, sync_token: str, synced_at: datetime
    ) -> Connection: ...
    def fail_sync(
        self,
        connection_id: str,
        secret_ref: str,
        generation: int,
        sync_token: str,
        error: dict,
        failed_at: datetime,
    ) -> None: ...
    def delete_connection(self, connection_id: str) -> None: ...
    def connection_reference_count(self, connection_id: str) -> int: ...
    def mark_connection_projections_stale(
        self, connection_id: str, *, reset_health: bool = False
    ) -> None: ...
    def upsert_projection(self, projection: Projection) -> None: ...
    def finish_sync(self, connection_id: str, generation: int, complete: bool) -> int: ...
    def get_projection(self, projection_id: str) -> Projection | None: ...
    def get_projection_by_provider_id(self, connection_id: str, provider_id: str) -> Projection | None: ...
    def list_projections(
        self,
        *,
        connection_id: str | None = None,
        q: str | None = None,
        carrier: str | None = None,
        city: str | None = None,
        health: str | None = None,
        enabled: bool | None = None,
        offset: int = 0,
        limit: int = 50,
    ) -> tuple[list[Projection], int]: ...
    def save_projection(self, projection: Projection, expected_revision: int) -> None: ...
    def projection_references(self, projection_id: str) -> tuple[list[tuple[str, str]], list[tuple[str, str]]]: ...
    def add_group(self, group: ProxyGroup) -> None: ...
    def get_group(self, group_id: str) -> ProxyGroup | None: ...
    def list_groups(self, *, q: str | None, offset: int, limit: int) -> tuple[list[ProxyGroup], int]: ...
    def save_group(self, group: ProxyGroup, expected_revision: int) -> None: ...
    def delete_group(self, group_id: str) -> None: ...
    def group_references(self, group_id: str) -> list[tuple[str, str]]: ...
    def get_projections(self, projection_ids: Sequence[str]) -> list[Projection]: ...
    def get_group_resolution(self, group_id: str, request_id: str) -> Projection | None: ...
    def list_group_candidates(self, group_id: str) -> list[Projection]: ...
    def commit_group_resolution(
        self,
        group_id: str,
        request_id: str,
        projection_id: str,
        expected_revision: int,
        expected_cursor_revision: int,
    ) -> Projection: ...
    def save_health(
        self, projection_id: str, expected_revision: int, health: Health, checked_at: datetime
    ) -> None: ...


class ProxyUnitOfWork(Protocol):
    repository: ProxyRepository

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
