import {test,expect,navigate,settle} from './electron-fixture'

test('real sidecar: browser, nested kernels, proxy connection, model connection and settings',async({page})=>{
 await navigate(page,'浏览器配置')
 await expect(page.getByText('还没有浏览器配置')).toBeVisible()
 await page.getByRole('button',{name:'新建配置',exact:true}).first().click()
 const form=page.getByRole('dialog',{name:'新建浏览器配置',exact:true})
 await expect(form).toBeVisible()
 await page.getByRole('tab',{name:'浏览器环境'}).click()
 const language=page.getByRole('combobox',{name:'浏览器语言',exact:true})
 await language.fill('中文');await expect(page.getByRole('listbox')).toBeVisible()
 await page.keyboard.press('Escape');await expect(form).toBeVisible()
 await page.getByRole('tab',{name:'内核与代理'}).click()
 const manage=page.getByRole('button',{name:'管理内核',exact:true});await manage.click()
 const kernels=page.getByRole('dialog',{name:'CloakBrowser 内核管理'})
 await expect(kernels).toBeVisible();await expect(page.getByLabel('License Key')).toHaveAttribute('type','password')
 await page.keyboard.press('Escape');await expect(kernels).toHaveCount(0);await expect(manage).toBeFocused()
 await page.keyboard.press('Escape');await expect(form).toHaveCount(0)
 await navigate(page,'代理管理')
 await page.getByRole('button',{name:'连接 ProxyPanel',exact:true}).click()
 const key=page.getByLabel('API Key',{exact:true});await key.fill('fixture-only-not-a-real-key')
 await page.getByRole('button',{name:'显示密码',exact:true}).click();await expect(key).toHaveAttribute('type','text')
 await page.getByRole('button',{name:'隐藏密码',exact:true}).click();await expect(key).toHaveAttribute('type','password')
 await page.keyboard.press('Escape')
 await navigate(page,'模型管理');await page.getByRole('button',{name:'添加模型供应商'}).click()
 const wizard=page.getByRole('dialog',{name:'添加供应商'})
 await page.getByRole('button',{name:'下一步',exact:true}).click()
 await expect(page.getByLabel('服务地址')).toBeVisible();await expect(page.locator('input[type=password]')).toHaveCount(1)
 await page.keyboard.press('Escape');await expect(wizard).toHaveCount(0)
 await navigate(page,'设置')
 const zoom=page.getByRole('combobox',{name:'界面缩放'});await zoom.click();await page.getByRole('option',{name:'110%',exact:true}).click()
 await expect(zoom).toHaveAttribute('data-choice-value','110')
 await page.getByText('连接详情',{exact:true}).click();await expect(page.getByText('Loopback HTTP')).toBeVisible()
 await page.getByRole('tab',{name:'关于',exact:true}).click();await page.getByRole('button',{name:'导出诊断信息',exact:true}).click()
 await expect(page.getByRole('dialog',{name:'导出诊断信息'})).toBeVisible();await expect(page.getByRole('button',{name:'选择保存位置',exact:true})).toBeEnabled()
})

test('real browser form: all prescribed window/zoom combinations keep footer and nested dialog reachable',async({page,desktop},testInfo)=>{
 await navigate(page,'浏览器配置');await page.getByRole('button',{name:'新建配置',exact:true}).first().click()
 const samples=[]
 for(const [width,height] of [[1280,800],[1440,900],[1024,768]])for(const zoom of [1,1.25,1.5,2]){
  await desktop.evaluate(({BrowserWindow},{width,height,zoom})=>{const win=BrowserWindow.getAllWindows()[0];win.setContentSize(width,height);win.webContents.setZoomFactor(zoom)},{width,height,zoom})
  await settle(page)
  const form=page.getByRole('dialog',{name:'新建浏览器配置',exact:true})
  const save=form.getByRole('button',{name:'创建配置',exact:true});await save.scrollIntoViewIfNeeded();await expect(save).toBeInViewport({ratio:1})
  await page.getByRole('tab',{name:'内核与代理'}).click();const manage=page.getByRole('button',{name:'管理内核',exact:true});await manage.scrollIntoViewIfNeeded();await settle(page);await manage.click()
  await expect(page.getByRole('dialog',{name:'CloakBrowser 内核管理'})).toBeInViewport({ratio:1})
  await page.keyboard.press('Escape');await expect(manage).toBeFocused()
  const horizontalOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth+1)
  expect(horizontalOverflow).toBe(false)
  samples.push({width,height,zoom,result:'passed'})
  if(zoom===2)await testInfo.attach(`${width}x${height}-200-percent`,{body:await page.screenshot(),contentType:'image/png'})
 }
 await page.keyboard.press('Escape')
 for(const name of ['总览','代理管理','模型管理','设置']){
  await navigate(page,name)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth+1)).toBe(false)
  await testInfo.attach(`low-window-${name}`,{body:await page.screenshot(),contentType:'image/png'})
 }
 await testInfo.attach('zoom-matrix',{body:JSON.stringify(samples,null,2),contentType:'application/json'})
})
