from datetime import datetime
from typing import Protocol

from .models import (
    DiscoveryResult,
    LocalModel,
    ModelOptionRecord,
    ModelProvider,
    ModelTestResult,
    ProviderConnection,
)


class ModelGateway(Protocol):
    async def discover(
        self, connection: ProviderConnection, secret: str
    ) -> DiscoveryResult: ...

    async def test_model(
        self, connection: ProviderConnection, secret: str, model_key: str
    ) -> ModelTestResult: ...


class ModelRepository(Protocol):
    def list_providers(self) -> list[ModelProvider]: ...
    def get_provider(self, provider_id: str) -> ModelProvider | None: ...
    def get_provider_by_name(self, name: str) -> ModelProvider | None: ...
    def add_provider(self, provider: ModelProvider) -> None: ...
    def update_provider(
        self, provider: ModelProvider, expected_updated_at: datetime | None = None
    ) -> bool: ...
    def remove_provider(
        self, provider_id: str, expected_updated_at: datetime | None = None
    ) -> bool: ...
    def get_model(self, model_id: str) -> LocalModel | None: ...
    def get_model_by_key(
        self, provider_id: str, model_key: str
    ) -> LocalModel | None: ...
    def add_model(self, model: LocalModel) -> None: ...
    def update_model(self, model: LocalModel) -> None: ...
    def remove_model(self, model_id: str) -> bool: ...
    def list_options(self) -> list[ModelOptionRecord]: ...
    def add_cleanup(self, secret_ref: str) -> None: ...
    def remove_cleanup(self, secret_ref: str) -> None: ...
    def list_cleanup(self) -> list[str]: ...
    def is_secret_ref_live(self, secret_ref: str) -> bool: ...
