from collections.abc import Awaitable, Callable
from typing import Any, Protocol

from autoflow.domain.workflows.run_validation import PreparedWorkflow


class AndroidError(Exception):
    def __init__(self, code: str, message: str, status: int = 409) -> None:
        super().__init__(message)
        self.code, self.message, self.status = code, message, status


class DeviceRepository(Protocol):
    def list(self) -> list[dict[str, Any]]: ...
    def get(self, device_id: str) -> dict[str, Any]: ...
    def save(self, device: dict[str, Any]) -> None: ...
    def claim(self, device_id: str, run_id: str) -> dict[str, Any]: ...


class AndroidRuntime(Protocol):
    async def environment(self) -> dict[str, Any]: ...
    async def preview(self, device: dict[str, Any]) -> bytes: ...
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    async def inspect(self, device: dict[str, Any]) -> dict[str, Any]: ...
    async def connect(self, device: dict[str, Any], save: Callable[[], None]) -> None: ...
    async def command(self, operation: str, args: dict[str, Any], timeout: float) -> bytes: ...
    async def open_window(self, title: str) -> None: ...
    async def close_window(self) -> None: ...
    def window_open(self) -> bool: ...
    async def disconnect(self) -> None: ...
    async def recover(self, device: dict[str, Any]) -> None: ...
    def new_device(self, config: dict[str, Any]) -> dict[str, Any]: ...
    async def manage(self, device: dict[str, Any], request: dict[str, Any], stage: Callable[[str], None], save: Callable[[], None]) -> None: ...


class AndroidWorkflowLauncher(Protocol):
    async def execute(self, run_id: str, prepared: PreparedWorkflow,
                      on_event: Callable[[dict[str, Any]], Awaitable[None]],
                      command: Callable[[dict[str, Any]], Awaitable[dict[str, Any]]]) -> dict[str, Any]: ...
    async def stop(self, run_id: str) -> None: ...
