"""Write the executor configuration key schema (remediation M2 R2-11).

Two generated copies of the same derivation: a Python snapshot the runtime reads without parsing
executor sources, and a JSON file for the Studio. ``--check`` fails when either is stale.
Usage: ``python -m autoflow.bootstrap.executor_schema_export [--check]``.
"""

import json
import sys
from pathlib import Path

from autoflow.application.workflows.config_schema import (
    COMMON_NODE_KEYS,
    export_schema,
    production_config_schema,
)

_ROOT = Path(__file__).resolve().parents[5]
SNAPSHOT = _ROOT / "apps/backend/src/autoflow/application/workflows/config_schema_snapshot.py"
STUDIO = _ROOT / "apps/desktop/src/renderer/domains/workflows/generated/executor-config-keys.json"


def render_snapshot() -> str:
    lines = [
        '"""Generated by ``python -m autoflow.bootstrap.executor_schema_export``; do not edit."""',
        "",
        "READ_KEYS: dict[str, frozenset[str]] = {",
    ]
    for module_type, keys in sorted(production_config_schema().items()):
        inner = ", ".join(f'"{key}"' for key in sorted(keys))
        lines.append(f'    "{module_type}": frozenset({{{inner}}}),' if keys else f'    "{module_type}": frozenset(),')
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_studio() -> str:
    payload = {"commonKeys": sorted(COMMON_NODE_KEYS), "nodes": export_schema()}
    return json.dumps(payload, ensure_ascii=False, indent=1, sort_keys=True) + "\n"


def main(argv: list[str]) -> int:
    outputs = {SNAPSHOT: render_snapshot(), STUDIO: render_studio()}
    if "--check" in argv:
        stale = [path for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
        for path in stale:
            sys.stderr.write(f"executor config schema is stale: {path}\n")
        return 1 if stale else 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
