"""Publish frontend service contracts without installing automation business routes."""

from typing import Any

from pydantic.json_schema import models_json_schema

from . import workflow_studio_schemas as schemas

STUDIO_SCHEMAS = (
    schemas.StudioRetentionConfig,
    schemas.StudioRetentionUpdate,
    schemas.StudioRetentionLoaded,
    schemas.StudioRetentionSaved,
    schemas.StudioRetentionUsageResponse,
    schemas.StudioRetentionCleanup,
    schemas.StudioCredentialList,
    schemas.StudioCredentialNames,
    schemas.StudioCredentialUpsertRequest,
    schemas.StudioCredentialSaved,
    schemas.StudioCredentialRenameRequest,
    schemas.StudioCredentialConfirmed,
    schemas.StudioCredentialFieldsCommand,
    schemas.StudioCredentialFieldsConfirmed,
    schemas.StudioBrowserPages,
    schemas.StudioBrowserPageCommand,
    schemas.StudioRecordingReviewWrite,
    schemas.StudioRecordingReview,
    schemas.StudioRecorderStartRequest,
    schemas.StudioRecorderReadRequest,
    schemas.StudioRecorderStarted,
    schemas.StudioRecorderStatus,
    schemas.StudioRecorderBatch,
    schemas.StudioRecorderStopped,
    schemas.StudioFolderSelectRequest,
    schemas.StudioFileSelectRequest,
    schemas.StudioPathSelectionResult,
    schemas.StudioDebugPauseContext,
    schemas.StudioDebugControlRequest,
    schemas.StudioDebugControlReceipt,
    schemas.StudioDebugControlLookup,
    schemas.StudioDebugVariableChange,
    schemas.StudioDebugVariablesRequest,
    schemas.StudioDebugVariablesReceipt,
    schemas.StudioPickerSessionStartRequest,
    schemas.StudioPickerSessionRequest,
    schemas.StudioPickerSessionState,
    schemas.StudioMcpConfig,
    schemas.StudioMcpConfigResponse,
    schemas.StudioMcpSaveRequest,
    schemas.StudioMcpSaved,
    schemas.StudioMcpStatus,
    schemas.StudioMcpReloadRequest,
    schemas.StudioMcpReloaded,
    schemas.StudioMcpCommandLookup,
    schemas.StudioModuleRequiredFields,
    schemas.StudioCommandReceipt,
    schemas.StudioCommandLookup,
    schemas.StudioExecutionLogEntry,
    schemas.StudioExecutionLogPage,
    schemas.StudioWorkflowRunSummary,
    schemas.StudioWorkflowRunPage,
    schemas.StudioRunResultRow,
    schemas.StudioRunResultPage,
    schemas.StudioRunResultValue,
    schemas.StudioImageAsset,
    schemas.StudioImageUploadResult,
    schemas.StudioImageMutationResult,
    schemas.StudioImageRenameResult,
    schemas.StudioImageFolderCreated,
    schemas.StudioImageFolderRenamed,
    schemas.StudioImageFolderDeleted,
    schemas.StudioImageMoved,
    schemas.StudioInputPromptRequest,
    schemas.StudioInputPromptResult,
    schemas.StudioInputPromptState,
    schemas.StudioSelectorTestRequest,
    schemas.StudioSelectorTestResult,
    schemas.StudioSimilarPickerResult,
    schemas.StudioBrowserStatus,
    schemas.StudioBrowserScriptContext,
    schemas.StudioBrowserScriptRequest,
    schemas.StudioBrowserScriptState,
    schemas.StudioClaimedRequestState,
    schemas.StudioRequestClaim,
    schemas.StudioSpeechRequest,
    schemas.StudioSpeechState,
    schemas.StudioSpeechResult,
    schemas.StudioJsScriptRequest,
    schemas.StudioJsScriptState,
    schemas.StudioJsScriptClaim,
    schemas.StudioJsScriptResult,
    schemas.StudioVariableTrackingResult,
    schemas.StudioVariableTrackingCleared,
    schemas.StudioRunVariableTrackingRecord,
    schemas.StudioRunVariableTrackingPage,
    schemas.StudioRunVariableTrackingCleared,
)


def add_workflow_studio_schemas(document: dict[str, Any]) -> None:
    _, definitions = models_json_schema(
        [(model, "validation") for model in STUDIO_SCHEMAS],
        ref_template="#/components/schemas/{model}",
    )
    target = document.setdefault("components", {}).setdefault("schemas", {})
    for name, definition in definitions.get("$defs", {}).items():
        target.setdefault(name, definition)
